### ISSUE TITLE
encoded field not respected Path parameters with slashes

### ISSUE THREAD

**Issue by jakeswenson** [square/retrofit#1546] opened 2016-01-29 22:03 UTC
Using version 2.0-beta2 i'm trying to send a parameter that appends to the URI path and the path parameter is still being encoded. 

### Example api
```
    @PUT("api/metadata/{metadataPath}")
    Call<ResponseBody> setMetadata(
            @Path(value = "metadataPath", encoded = true) String metadataPath,
            @Body Object body);
```

calling with `metadataPath = "foo/bar/baz"` results in a url like `api/metadata/foo%2Fbar%2Fbaz`

I looked into `RequestBuilder` and se the offending block:
```
  static String canonicalize(String input, boolean alreadyEncoded) {
    int codePoint;
    for (int i = 0, limit = input.length(); i < limit; i += Character.charCount(codePoint)) {
      codePoint = input.codePointAt(i);
      if (codePoint < 0x20 || codePoint >= 0x7f
          || PATH_SEGMENT_ENCODE_SET.indexOf(codePoint) != -1 // <---- This should probably also check !alreadyEncoded
          || (codePoint == '%' && !alreadyEncoded)) {
        // Slow path: the character at i requires encoding!
        Buffer out = new Buffer();
        out.writeUtf8(input, 0, i);
        canonicalize(out, input, i, limit, alreadyEncoded);
        return out.readUtf8();
      }
    }

    // Fast path: no characters required encoding.
    return input;
  }
```

A bigger question would be if the API creator says this value is already encoded, why is canonicalize doing anything at all?

this is slightly related to #1364, and fixing this may allow and easy workaround.

Also this seems like something you'd want to change as a part of 2.0, since it will be a breaking change, it'd be nice to get it into to the next beta/release.

**Comment by jakeswenson** [comment] 2016-01-29 22:09
If there are no objections, i can submit a pull request changing the condition to check already encoded.
thoughts on making the condition:

```
static boolean shouldEncodeCodePoint(int codePoint) {
    return codePoint < 0x20 || codePoint >= 0x7f
          || PATH_SEGMENT_ENCODE_SET.indexOf(codePoint) != -1
          || codePoint == '%';
}

... canonicalize(...) {...

if(!alreadyEncoded && shouldEncodeCodePoint(codePoint)) {
    ...
}
```

Thoughts?

**Comment by JakeWharton** [comment] 2016-01-29 22:10
> this is slightly related to #1364

it looks like an exact duplicate of this issue. is there any difference?

**Comment by jakeswenson** [comment] 2016-01-29 22:12
It looks that this is different in that #1364 is requesting array support, no? this is only a bug to fix the encoding parameter.

**Comment by jakeswenson** [comment] 2016-01-29 22:15
Also i could see how multiSegment = true is different from encoded = true. 
multi-segment being true means not to encode path separators like `/` but encode the components in between. 
encoded = true should mean trust whatever value i send in. Or at least that was my assumption.

**Comment by jakeswenson** [comment] 2016-01-29 22:18
At the very least we should update the documentation to reflect if encoded is not the case:
```Path.java

  /**
   * Specifies whether the argument value to the annotated method parameter is already URL encoded.
   */
  boolean encoded() default false;
```

If the value is already URL encoded why is further encoding done?

**Comment by JakeWharton** [comment] 2016-01-29 22:20
Because you are violating a path segment boundary and the system was designed for segment-based replacement, not multi-segment replacement.

**Comment by JakeWharton** [comment] 2016-01-29 22:20
I really don't care because I have never used this feature and I never plan to. I'm up for whatever will produce less support requests in the future, and if that's encoded=true means that you can cross path segment boundaries contrary to the behavior of `HttpUrl` then I'm all for it.

**Comment by JakeWharton** [comment] 2016-01-29 22:22
This issue is exactly a duplicate of the linked one, though, so let's continue any needed discussion there. The use of arrays was merely a suggestion of encoding the semantics of explicitly providing multiple pre-encoded path segments.

**Closed by JakeWharton** 2016-01-29 22:22 UTC

**Comment by jakeswenson** [comment] 2016-01-29 22:29
Thanks! will move the discussion of encoded to the other bug. Does this mean this fix won't make it into 2.0?

**Comment by JakeWharton** [comment] 2016-01-29 22:30
If a PR were to show up with a test, it will be merged...

**Comment by jakeswenson** [comment] 2016-01-29 22:31
Thank you Jake. PR forthcoming.
