### ISSUE TITLE
Could not work when open minifyEnabled...

### ISSUE THREAD

**Issue by jasonni** [square/retrofit#747] opened 2015-02-11 04:52 UTC
There have a question about minifyEnabled,
the *proguard-rules.pro* file has add the dontwarn and keep class,
gradle build is success too,
but run app meet a problem in Callback function,
the weatherResponse's data is null in minifyEnabled = true,
but the data is good in minifyEnabled = false.
below is my code,
[https://gist.github.com/jasonni/e44f93f236d47f08b748](https://gist.github.com/jasonni/e44f93f236d47f08b748)

**Comment by sohayb** [comment] 2015-02-11 08:03
What do you use for Json parsing? do you use default Gson?

**Comment by jasonni** [comment] 2015-02-11 08:20
Hi sohayb,
I use default Gson !

**Comment by sohayb** [comment] 2015-02-11 08:49
I think that the problem is related to the Gson part of your Proguard rules file, can you post that so we can make sure it from it?
This is the right configuration of the Gson library (I think the problem that you didn't include a "keep class" for your "WeatherResponse" class or other Gson parsed classes.
````
##---------------Begin: proguard configuration for Gson  ----------
# For using GSON @Expose annotation
-keepattributes *Annotation*
# This is for Gson use. Explicitly preserve all serialization members. The Serializable interface
# is only a marker interface, so it wouldn't save them.
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class your.models.package.** { *; }
##---------------End: proguard configuration for Gson  ----------
````

**Comment by jasonni** [comment] 2015-02-11 13:25
hi sohayb,
thanks for your help,
the Gson's proguard setting is not work,
but I move my **WeatherResponse** class to my **bean** package
and add the proguard like below
``` java
-keep class info.jasonni.retrofitdemo.bean.** { *; }
```
It's work and my proguard below !
[https://gist.github.com/jasonni/e44f93f236d47f08b748#file-proguard-rules-pro](https://gist.github.com/jasonni/e44f93f236d47f08b748#file-proguard-rules-pro)

**Comment by sohayb** [comment] 2015-02-11 13:50
so your problem is solved now? Glad to help :)
Please close the issue if so..

**Closed** 2015-02-11 13:51 UTC
