### ISSUE TITLE
java.net.ProtocolException: Expected ':status' header not present

### ISSUE THREAD

**Issue by archanapareta** [square/retrofit#2720] opened 2018-03-28 13:25 UTC
Hello Support,

I am using below libraries to call  APIs on https sever -
 compile 'com.squareup.retrofit:retrofit:1.9.0'
 compile 'com.squareup.okhttp:okhttp:2.4.0'
 compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'

Before 3-4 days all working fine. But suddenly from yesterday I am getting **java.net.ProtocolException: Expected ':status' header not present** this exception. To resolve this issue I have to **upgrade okhttp and retrofit libraries** or need to add **okHttpClient.setProtocols(Arrays.asList(Protocol.HTTP_1_1))** this line.

Can you please help me to find out the reason behind this? What changes have been made in both okhttp and okhttp3 libraries regarding this?

Please update me asap.
Thanks.

**Comment by JakeWharton** [comment] 2018-03-28 13:27
Dupe of #2718. Those library versions are many years old. Please update.

**Closed by JakeWharton** 2018-03-28 13:27 UTC

**Comment by archanapareta** [comment] 2018-03-28 13:34
Yes I will update it,  but already published builds on Play Store stopped working. So I want to know the reason that you have removed support to old version or not?

**Comment by JakeWharton** [comment] 2018-03-28 13:39
It sounds like the server you are talking to has changed its configuration which prevents those really old versions from working.

**Comment by archanapareta** [comment] 2018-03-28 13:50
We have not changed server configuration.

**Comment by swankjesse** [comment] 2018-03-29 02:13
You upgraded some servers to HTTP/2 and that exercises a bug in the old software you’re running.

**Comment by hiteshcla00** [comment] 2018-05-25 16:17
i am also getting this error but when i update dependencies . then getting this all errors below link
https://stackoverflow.com/questions/50447511/android-when-updating-retrofit-2-9-1-and-okhttp-3-x-x-the-json-converter-library

https://stackoverflow.com/questions/50453522/error-when-trying-to-upgrade-retrofit-library
