### ISSUE TITLE
[Feature Request] Working with flavor. (API interfaces must not extend other interfaces.)

### ISSUE THREAD

**Issue by XieEDeHeiShou** [square/retrofit#2644] opened 2018-02-09 15:15 UTC
I want to use gradle's flavor featrue to avoid copy and paste, but when I test my application, it just crashed when it try to create a service who is extend form a parent service..

I have to fix my services form: [API interfaces must not extend other interfaces.](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Utils.java#L316) (by copy and paste parent service's methods to every child class, and then remove parent service) 

Was is possible to add an annotation to mark an interface is a retrofit service and make is extend-able?

**Comment by NightlyNexus** [comment] 2018-02-09 23:31
Duplicate of #504 
You can subscribe there for updates.

**Closed** 2018-02-09 23:33 UTC
