### ISSUE TITLE
Unexpected character ('﻿' (code 65279 / 0xfeff)) using JacksonConverterFactory

### ISSUE THREAD

**Issue by xding123** [square/retrofit#1896] opened 2016-07-05 16:19 UTC
I am evaluating retrofit 2.1with JacksonConverterFactory. But I got Unexpected character ('﻿' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

I used to consume the same Web Service successfully using HttpURLConnection with Jackson and it has been working. Do you have any suggestion?

**Comment by JakeWharton** [comment] 2016-07-06 19:50
This is caused by a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). I'll have to see how we're handing off to Jackson if we can optimize for allowing it to skip the BOM.

**Comment by JakeWharton** [comment] 2016-07-06 19:50
Related to #1875.

**Comment by xding123** [comment] 2016-07-07 15:59
Thanks Jake for the responding, I am looking at the JacksonResponseBodyConverter<T> and think charStream might cause the JsonParseException because of the BOM. if using byteStream, it might fix the issue.
Is there any suggestion on how I might work around it using Retrofit 2.1 with JacksonConverterFactory?

From: Jake Wharton
Reply-To: square/retrofit
Date: Wednesday, July 6, 2016 at 2:50 PM
To: square/retrofit
Cc: Steve Ding, Author
Subject: Re: [square/retrofit] Unexpected character ('' (code 65279 / 0xfeff)) using JacksonConverterFactory (#1896)


This is caused by a BOM<https://urldefense.proofpoint.com/v2/url?u=https-3A__en.wikipedia.org_wiki_Byte-5Forder-5Fmark&d=BQMCaQ&c=8nlCJSrIh_dUFbYhzMsm7vFNxJKfP9AUkTINxOasPog&r=lOR3FdWEjwxX5o3VM1ARNrtqZa0hX2tk37yvmPJAy60&m=WOuXI9IetOY5aZ6PGOj7t346QvUQDWCTnyd_xPHlbLA&s=C2I6x3b-zClDjO7LtNk6FFHWl0CAqa2jaDYcU_bhb6k&e=>. I'll have to see how we're handing off to Jackson if we can optimize for allowing it to skip the BOM.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_square_retrofit_issues_1896-23issuecomment-2D230886184&d=BQMCaQ&c=8nlCJSrIh_dUFbYhzMsm7vFNxJKfP9AUkTINxOasPog&r=lOR3FdWEjwxX5o3VM1ARNrtqZa0hX2tk37yvmPJAy60&m=WOuXI9IetOY5aZ6PGOj7t346QvUQDWCTnyd_xPHlbLA&s=thNj1PyhSR4XnbULycXblg3TGMjjO2q9GVhg-GqFEoM&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe_ATXPkQHDG5UyD6DDOkTZAmB6wcbKXXbsks5qTAcjgaJpZM4JFSZY&d=BQMCaQ&c=8nlCJSrIh_dUFbYhzMsm7vFNxJKfP9AUkTINxOasPog&r=lOR3FdWEjwxX5o3VM1ARNrtqZa0hX2tk37yvmPJAy60&m=WOuXI9IetOY5aZ6PGOj7t346QvUQDWCTnyd_xPHlbLA&s=U14bdkxiFxuMyG1xeH422cNRgg7h-li9WX-hEKNqeQE&e=>.
All e-mail sent to and from this address will be retained by the Scottrade corporate e-mail system and is subject to review by someone other than the recipient. E-mail transmissions may not be secure; contact us at 1-800-619-SAVE for more information.

**Comment by xding123** [comment] 2016-07-07 21:48
I see your point.

The web service returns response as UTF-8 with BOM which is not recommended and unnecessary. However, as web service consumer, there seems nothing we could do about that. To use Retrofit with Jackson, I hope the JacksonConverterFactory will handle this in the future.

Thanks.

From: Jake Wharton
Reply-To: square/retrofit
Date: Thursday, July 7, 2016 at 11:02 AM
To: square/retrofit
Cc: Steve Ding, Author
Subject: Re: [square/retrofit] Unexpected character ('' (code 65279 / 0xfeff)) using JacksonConverterFactory (#1896)

If byteStream is used then the charset specified by the response will be
ignored and you'll get malformed characters.

All e-mail sent to and from this address will be retained by the Scottrade corporate e-mail system and is subject to review by someone other than the recipient. E-mail transmissions may not be secure; contact us at 1-800-619-SAVE for more information.

**Comment by JakeWharton** [comment] 2016-07-08 01:14
Closing in favor of #1875 since this problem plagues multiple converters. I'll re-purpose that issue to cover BOM handling for _all_ converters and outline what our approach will be.

Thanks for reporting!

**Closed by JakeWharton** 2016-07-08 01:14 UTC
Labels: Bug

**Comment by xding123** [comment] 2016-07-08 13:39
Just add a little more information here: I consumed the exactly same web service API using retrofit + GsonConverterFactory, no issue. Hope this helps.

From: Jake Wharton
Reply-To: square/retrofit
Date: Thursday, July 7, 2016 at 8:15 PM
To: square/retrofit
Cc: Steve Ding, Author
Subject: Re: [square/retrofit] Unexpected character ('' (code 65279 / 0xfeff)) using JacksonConverterFactory (#1896)


Closing in favor of #1875<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_square_retrofit_issues_1875&d=BQMCaQ&c=8nlCJSrIh_dUFbYhzMsm7vFNxJKfP9AUkTINxOasPog&r=lOR3FdWEjwxX5o3VM1ARNrtqZa0hX2tk37yvmPJAy60&m=QJ7BCfjxkrQHcxX06wwTusNi2uou57oFpynMDHoLb-s&s=LhFX8Tx13H0t5qglayjIOxKH3npBYBr90-tTXDeTYUU&e=> since this problem plagues multiple converters. I'll re-purpose that issue to cover BOM handling for all converters and outline what our approach will be.

Thanks for reporting!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_square_retrofit_issues_1896-23issuecomment-2D231251811&d=BQMCaQ&c=8nlCJSrIh_dUFbYhzMsm7vFNxJKfP9AUkTINxOasPog&r=lOR3FdWEjwxX5o3VM1ARNrtqZa0hX2tk37yvmPJAy60&m=QJ7BCfjxkrQHcxX06wwTusNi2uou57oFpynMDHoLb-s&s=OvPBJ0UPXJU8SIsdEcMz8QPzj3X6l-TrG1Wf4o3guwc&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe_ATXPkVi0MEcHbAcT0mGeCfS24FgNbr29ks5qTaSrgaJpZM4JFSZY&d=BQMCaQ&c=8nlCJSrIh_dUFbYhzMsm7vFNxJKfP9AUkTINxOasPog&r=lOR3FdWEjwxX5o3VM1ARNrtqZa0hX2tk37yvmPJAy60&m=QJ7BCfjxkrQHcxX06wwTusNi2uou57oFpynMDHoLb-s&s=RVix-G5ZPxnq8w7ujniq7gY1TInwx_AquODaEB45opg&e=>.
All e-mail sent to and from this address will be retained by the Scottrade corporate e-mail system and is subject to review by someone other than the recipient. E-mail transmissions may not be secure; contact us at 1-800-619-SAVE for more information.

**Comment by JakeWharton** [comment] 2016-07-08 14:34
That's really strange, since we use the same charStream() method to hand
data to Gson. Maybe it just silently consumes it?

**Comment by xding123** [comment] 2016-08-02 13:49
Hi Jake,

If there are more than 100 endpoints in the application using the same base url, what is the best strategy using retrofit.

Is it good practice to put them all in one interface and create only one retrofit instance for all the calls or It’s better to group the endpoints into several interfaces and therefore creating several instances?

Best Regards,

Steve Ding
All e-mail sent to and from this address will be retained by the Scottrade corporate e-mail system and is subject to review by someone other than the recipient. E-mail transmissions may not be secure; contact us at 1-800-619-SAVE for more information.

**Comment by Bhavdip** [comment] 2017-02-17 07:47
Thank you @JakeWharton 
If someone having the same problem, Try to upgrade your dependence for retrofit `com.squareup.retrofit2:converter-jackson:2.0.2` like below:
```
 compile ('com.squareup.retrofit2:converter-jackson:2.0.2') {
      // exclude Retrofit’s OkHttp peer-dependency module and define your own module import
      exclude module: 'okhttp'
    }
    compile 'com.squareup.okhttp3:logging-interceptor:3.6.0'
```
