### ISSUE TITLE
retrofit with protobuf,but error by "had no PARSER field"

### ISSUE THREAD

**Issue by shibenli** [square/retrofit#2145] opened 2017-01-05 09:36 UTC
Caused by: java.lang.IllegalArgumentException: Found a protobuf message but com.vcredit.zj.bean.proto.BookOuterClass$Book had no PARSER field.
                                                                         at retrofit2.converter.protobuf.ProtoConverterFactory.responseBodyConverter(ProtoConverterFactory.java:69)
                                                                         at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:325)
                                                                         at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:308)
                                                                         at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:704)
                                                                         at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:167) 
                                                                         at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166) 
                                                                         at retrofit2.Retrofit$1.invoke(Retrofit.java:145) 
                                                                         at java.lang.reflect.Proxy.invoke(Proxy.java:393) 

This is pb:
```
syntax = "proto3";
option java_package = "com.vcredit.zj.bean.proto";
package bean;
message Book {
    int32 id = 1;
    string name = 2;
    string desc = 3;
}
```

and i have debuged giving me flowwing result

![22222](https://cloud.githubusercontent.com/assets/7353956/21675569/38bb2a18-d36d-11e6-82b4-680b15650f37.jpg)

**Comment by swankjesse** [comment] 2017-01-05 14:48
Does Retrofit support proto3? You might need to make a proto3 converter factory.

**Comment by JakeWharton** [comment] 2017-01-05 15:52
This is a dupe of #1821 and was fixed by #1953. We should have Retrofit 2.2.0 out in the next two weeks. If you're able, you should be able to use 2.2.0-SNAPSHOT of the protobuf converter until then.

**Closed by JakeWharton** 2017-01-05 15:52 UTC

**Comment by shibenli** [comment] 2017-01-06 02:45
i got the same error when i use  proto2

**Comment by shibenli** [comment] 2017-01-06 03:23
And i used protobuf-lite in Android but protobuf-java in java service.I had got the right data by  chrom
