### ISSUE TITLE
cannot make a new request because the previous response is still open: please call response.close()

### ISSUE THREAD

**Issue by nihp** [square/retrofit#3478] opened 2020-10-13 12:16 UTC
I am using retrofit2 and tried to hit the call.

But I am getting the error as cannot make a new request because the previous response is still open: please call response.close().

My request is like 
```

serviceRequestTypesResponseCall.enqueue(new RetrofitCallback<ServiceRequestTypesResponse>(retrofit) {
        @Override
        public void onResponse(RetrofitResult<ServiceRequestTypesResponse> result) {

            // get url from response and enqueue nested call
            detailedServiceRequestTypeCall.enqueue(new RetrofitCallback<DetailedServiceRequestType>(retrofit) {
                @Override
                public void onResponse(RetrofitResult<DetailedServiceRequestType> result) {
                    // this is being reached when cancelled
                }

                @Override
                public void onFailure(RetrofitResult<DetailedServiceRequestType> error) {
                    // do something
                }

            });
        }

        @Override
        public void onFailure(RetrofitResult<ServiceRequestTypesResponse> error) {
            // do something
        }
    });
```

**Comment by Mezah** [comment] 2020-10-16 03:48
This error message comes from okHttp not retrofit as you are trying to chain a call without finalizing the previous one. You can try another chaining method like using an interceptor or RxJava for complex chaining scenarios

**Comment by JakeWharton** [comment] 2020-10-16 12:37
Yeah without a test case or reproducing sample it's impossible to see where the failure is, but ultimately it's not from Retrofit but your integration code. Making concurrent enqueue's should in general be fine, but based on the types it's clear you have a bunch of custom integration code as the types seen above are not those provided by the library directly.

**Comment by nihp** [comment] 2020-10-20 13:33
My service is like

Steps:
1. First I will hit the login call to get the token (This has a separate retrofit without setting the header) (I got token as expected)
2. So I have set that token in the below call and tried to get the user profile.(Here it will show the previous response is open please close respose.close().

Note: enqueue method is like nested calls.


```
public class RetrofitRequest<retrofit> {
    private  Retrofit retrofit = null;

    public static Retrofit getClient() {
        Gson gson = new GsonBuilder()
                .setLenient()
                .create();
        OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(SERVER_API)
                .client(createOkHttpClient())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build();

        return retrofit;
    }

    protected static boolean isTokenRequired() {
        return true;
    }


    private static OkHttpClient createOkHttpClient() {
        final OkHttpClient.Builder httpClient = new OkHttpClient.Builder();

        if (isTokenRequired()) {
            if (!TextUtils.isEmpty(User.getInstance().getToken())) {
                String token = User.getInstance().getToken();
                
                httpClient.addInterceptor(
                        new Interceptor() {
                            @Override
                            public Response intercept(Chain chain) throws IOException {
                                Request newRequest = null;
                                   
                                    newRequest = chain.request().newBuilder()
                                            .header("Authorization", "Bearer " + token)
                                            .build();
                                return chain.proceed(newRequest);

                            }
                        });
             });
            } else {
                throw new IllegalStateException("No Token");
            }
        }
        return httpClient.build();
    }
}


```

**Comment by Voto** [comment] 2021-03-08 15:05
I don't have a solution but an interesting hint to this issue. We've got that error as well but it came from a retrofit update.

We updated from 2.5.0 to 2.9.0. With 2.9.0 we have this exception, with 2.5.0 everything works fine.
Can you acknowledge that its exception does not occur with this version?

**Comment by blinkev** [comment] 2021-10-04 15:21
Today got the same error "cannot make a new request because the previous response is still open" in my TokenRefresher class.

People have said that on the latest Retrofit versions we should close initial response with initialResponse.close() method. https://medium.com/@113408/this-is-a-nice-implementation-of-the-authinterceptor-however-on-newer-version-of-okhttp-retrofit-9cf20477e2af

**Comment by Deepanr20** [comment] 2021-10-07 04:11
We are using retrofit2 2.9.0v. We are facing this issue suddenly but not able to reproduce. we found this crash in Crashlytics. In default, the response is closed in callable finally block even though should we close the response manually? 

Or any other solution for this issue?

**Fatal Exception: java.lang.IllegalStateException
cannot make a new request because the previous response is still open: please call response.close()**

okhttp3.internal.connection.Transmitter.newExchange (Transmitter.java:164)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:41)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:94)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:88)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
**ai.haptik.android.sdk.common.OkHttpClientFactory$1.intercept (OkHttpClientFactory.java:101)**
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
ai.haptik.android.sdk.common.a.intercept (a.java:30)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:229)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:172)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)

**Comment by Voto** [comment] 2021-10-07 05:36
After some code iterations, we were able to fix this bug with retrofitVersion = 2.9.0

Hope it helps

```kotlin
override fun intercept(chain: Interceptor.Chain): Response {
        return if (currentToken.isEmpty()) {
            getTokenAndRetry(chain)
        } else {
           /** some code **/

            val isFailed = response.isSuccessful.not()
            if (isFailed) {
                // call was not successful --> current token was deleted -> get token and try again
                response.close() // <---- CLOSE HERE!!
                return getTokenAndRetry(chain) // <-- see next code snippet
            }

            return response
        }
    }

private fun getTokenAndRetry(chain: Interceptor.Chain): Response {

    /** SOME CODE **/

    val refreshResponse = chain.proceedDeletingTokenOnError(refreshTokenRequest)
        return when (refreshResponse.isSuccessful) {
            true -> {
               /** some code in good case **/ 
            }
            false -> {
                // close is error case
                refreshResponse.close() // <-- CLOSE HERE
                chain.proceedDeletingTokenOnError(chain.request())
            }
    }
}

```

**Comment by santiihoyos** [comment] 2021-12-13 11:26
> I had the same problem while implementing refreshToken as per this article https://medium.com/@emmanuelguther/android-refresh-token-with-multiple-calls-with-retrofit-babe5d1023a1 and update retrofit from 2.5.0 -> 2.9.0
> 
> Note that I only get the error when I build in the release environment

Same.It only happens on release build.

**Comment by blinkev** [comment] 2021-12-15 09:28
> I had the same problem while implementing refreshToken as per this article https://medium.com/@emmanuelguther/android-refresh-token-with-multiple-calls-with-retrofit-babe5d1023a1 and update retrofit from 2.5.0 -> 2.9.0
> 
> Note that I only get the error when I build in the release environment

Don't use the approach in specified medium article, it's extremely bad (see comments to the article)

**Comment by yaakov-lightricks** [comment] 2022-05-22 11:04
I can also confirm that we have this bug just in release build with retrofit `2.9.0`

**Comment by sanjeevirajm** [comment] 2022-07-08 07:09
https://github.com/square/okhttp/blob/b9267b0ce7a11440ccdd6b3e7d70c4ab9710a144/okhttp/src/jvmMain/kotlin/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt#L101

close the previous response like they have closed in RetryAndFollowUpInterceptor.
response.body?.closeQuietly()

**Comment by rvp-diconium** [comment] 2024-02-22 12:16
> Found a solution from okhttp source itself. It works fine. Users aren't facing the crash after adding this line before calling chain.proceed again. response.body?.closeQuietly()
> 
> https://github.com/square/okhttp/blob/b9267b0ce7a11440ccdd6b3e7d70c4ab9710a144/okhttp/src/jvmMain/kotlin/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt#L101
> 
> close the previous response like they have closed it in RetryAndFollowUpInterceptor.
> 
> Note: don't use close(), instead use closeQuietly. the close() method might throw exception. IllegalStateException, other IOException which can be safely ignored.

I just noticed that `closeQuietly()` is part of the package `okhttp3.internal`, even if it's not `private` or `internal` should external applications really be using it?

**Comment by JakeWharton** [comment] 2024-02-22 12:51
No. Just call `close`, or use `use`.

**Closed by JakeWharton** 2024-02-22 12:51 UTC
Labels: Needs Info

**Comment by galwaychia** [comment] 2024-03-13 09:48
> No. Just call `close`, or use `use`.

If response.close() and then call chain.proceed, that means request the backend 2 times: first request occurs before close and the next request occurs after chain.proceed, right?
