### ISSUE TITLE
NoClassDefFoundError on Android 4.1.2

### ISSUE THREAD

**Issue by speciosus** [square/retrofit#1628] opened 2016-02-26 09:07 UTC
Hi, everybody.
I write because I have encountered a problem while using the retrofit2 library on Samsung Galaxy S2 (Android 4.1.2).
While performing any network request, the application dies with the following stack trace:

<code>
java.lang.ExceptionInInitializerError
at com.vwgroup.audiservice.bolts.TaskManager.registrationTask(TaskManager.java:41)
at com.vwgroup.audiservice.ui.activity.ImbServiceTest.performNetworkrequest(ImbServiceTest.java:49)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1619)
Caused by: java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder
at com.vwgroup.audiservice.network.ServiceGenerator.<clinit>(ServiceGenerator.java:24)
... 33 more
</code>

The same code run without any issue on Android 5.0, 5.1, 6

My Gradle dependencies are as follows:

<code>
    compile ('com.squareup.retrofit2:retrofit:2.0.0-beta4'){
        exclude group: 'com.android.support'
    }
    compile ('com.squareup.retrofit2:converter-gson:2.0.0-beta4'){
        exclude group: 'com.android.support'
    }
    compile ('com.squareup.retrofit2:converter-simplexml:2.0.0-beta4'){
        exclude module: 'xpp3'
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude group: 'com.android.support'
    }
    compile 'com.squareup.okhttp:okhttp:2.7.4'
</code>

Any help will be appreciated.

thanks

**Comment by PaijoRX** [comment] 2016-02-26 12:00
today i got same error after update to  version:
~~~
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta4'
~~~
previously i was using version :
~~~
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta2'
compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta2'
~~~
and everything running properly.

error :
~~~
Could not find class 'retrofit2.Retrofit$Builder'
~~~

code :
~~~
Retrofit retrofit = new Retrofit.Builder()
    .baseUrl("http://myserver.com")
    .addConverterFactory(GsonConverterFactory.create())
    build();
~~~

**Comment by audamob** [comment] 2016-02-26 23:10
I got same error using the beta4 version :
`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:support-v13:23.1.1'
    compile 'com.getbase:floatingactionbutton:1.9.0'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.lorentzos.swipecards:library:1.0.9'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta4'
}
`

And my ServiceGenerator : 
`public class ServiceGenerator {

    public static final String API_BASE_URL = "http://my_url.com";

    private static Retrofit.Builder builder =
            new Retrofit.Builder()
                    .baseUrl(API_BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create());

    /**
     * Instanciate Service
     * @param serviceClass
     */
    public static <S> S createService(Class<S> serviceClass) {
        Retrofit retrofit = builder.build();
        return retrofit.create(serviceClass);
    }
}
`

and i got this error : 

`Caused by: java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder
                                                              at com.wasten.service.ServiceGenerator.<clinit>(ServiceGenerator.java:13)
                                                              at com.wasten.activity.child.UserListActivity.getUserListData(UserListActivity.java:84) 
                                                              at com.wasten.activity.child.UserListActivity.onCreate(UserListActivity.java:54) 
                                                              at android.app.Activity.performCreate(Activity.java:5047) 
                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056) 
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117) 
                                                              at android.app.ActivityThread.access$700(ActivityThread.java:134) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                              at android.os.Looper.loop(Looper.java:137) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:4867) 
                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                              at java.lang.reflect.Method.invoke(Method.java:511) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774) 
                                                              at dalvik.system.NativeStart.main(Native Method) 
`

**Comment by artem-zinnatullin** [comment] 2016-02-26 23:30
Do you guys use `multidex`? If so, make sure that in the `Application.attachBaseContext()` you're initializing it correctly.

**Comment by PaijoRX** [comment] 2016-02-27 07:45
yup, i'm using multiDexEnabled true,
would you like to show the snippet?

**Comment by speciosus** [comment] 2016-02-27 15:04
Yes, I used multiDexEnabled true too :-)

**Comment by audamob** [comment] 2016-02-27 15:07
Yes, I used multiDexEnabled true too, but i don't that this is the cause of the problem,
I invalidate Cache, 
I deleted the cache gradle..
but i have always the problem, 
im using Android 4.1.2 and retrofit2.

i got always : 
`Caused by: java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder at ....`

**Comment by artem-zinnatullin** [comment] 2016-02-27 16:46
Use either `MultidexApplication` or initialize it manually. 

Here is documentation http://developer.android.com/tools/building/multidex.html

**Comment by PaijoRX** [comment] 2016-02-28 06:16
today, i have created new simple app using retrofit2 beta4 and used multiDexEnabled true. But the error not appear. my app running well.
But my other app using retrofit2 beta4 and multiDexEnabled true still error.

**Comment by audamob** [comment] 2016-02-28 06:25
Hi Guys,

I solved my problem by changing one dependancies,
the origin of this exception isn't retrofit2-beta4, but another libraby that use an older version of retrofit, so that create the conflict in the classpath during runtime.

retrofit solved the conflict problem by renaming package to retrofit2.

@PaijoRX can u paste here all your dependancies that you use in Gradle please ?

**Comment by PaijoRX** [comment] 2016-02-28 06:37
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com.simp.ams"
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile project(':swiperefreshlayoutlibrary')
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta4'
    compile 'com.android.support:design:23.1.1'
    compile 'com.google.android.gms:play-services:8.4.0'
}

**Comment by PaijoRX** [comment] 2016-02-28 06:49
finally i can solve my error.
remove multiDexEnabled true from gradle and replace compile 'com.google.android.gms:play-services:8.4.0' whit specific depedencies i used ('com.google.android.gms:play-services-location:8.4.0').

**Comment by JakeWharton** [comment] 2016-02-28 15:45
Closing since this was determined to be a build system problem and not a Retrofit bug.

**Closed by JakeWharton** 2016-02-28 15:45 UTC

**Comment by speciosus** [comment] 2016-03-15 15:01
Hello. 

Today I tested Retrofit2's new version. I added the following dependencies:

<code>
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        exclude group: 'com.android.support'
        transitive = true;
    }

    // -- Better Picker
    compile('com.code-troopers.betterpickers:library:2.0.3') {
        exclude group: 'com.android.support', module: 'support-v4'
    }

    // -- Parsing HTML Web Page
    compile files('src/main/java/com/vwgroup/audiservice/libs/ksoap2-android-assembly-3.4.0-jar-with-dependencies.jar')

    compile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:recyclerview-v7:23.2.1'
    compile 'com.android.support:gridlayout-v7:23.2.1'

    compile 'com.android.support:design:23.2.1'

    compile 'com.j256.ormlite:ormlite-core:4.48'
    compile 'com.j256.ormlite:ormlite-android:4.48'
    compile 'info.hoang8f:android-segmented:1.0.5'

    compile('com.squareup.picasso:picasso:2.5.2') {
        exclude group: 'com.android.support'
    }
    compile ('com.mcxiaoke.volley:library:1.0.19'){
//            exclude group: 'com.squareup.retrofit2'
    }

    compile ('com.google.maps.android:android-maps-utils:0.4'){
    }

    compile ('org.jsoup:jsoup:1.8.3'){
    }

    compile ('com.kbeanie:image-chooser-library:1.5.7@aar'){
    }

    compile ('ly.count.android:sdk:15.06'){
//        exclude group: 'com.squareup.retrofit2'
    }
    // -- Network with retrofit
    compile('com.squareup.retrofit2:retrofit:2.0.0') {
        exclude group: 'com.android.support'
    }
    compile('com.squareup.retrofit2:converter-gson:2.0.0') {
        exclude group: 'com.android.support'
    }
    compile('com.squareup.retrofit2:converter-simplexml:2.0.0') {
        exclude module: 'xpp3'
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude group: 'com.android.support'
    }

    compile ('com.squareup.okhttp:okhttp:2.7.4'){
    }
    // -- Parse bolts
    compile 'com.parse.bolts:bolts-android:1.2.1'
    compile('com.google.android.gms:play-services-gcm:8.3.0') {
        exclude module: 'bolts-android'
        exclude module: 'support-v4'
    }

    compile('com.google.android.gms:play-services-maps:8.3.0') {
        exclude module: 'bolts-android'
        exclude module: 'support-v4'
    }

    compile('com.google.android.gms:play-services-location:8.3.0') {
        exclude module: 'bolts-android'
        exclude module: 'support-v4'
    }
    // -- Push woosh integration
    compile('com.pushwoosh:pushwoosh:+') {
    }
</code>

error :

<code>
Could not find class 'retrofit2.Retrofit$Builder'
</code>


Code :

<code>
Retrofit retrofit = new Retrofit.Builder()
    .baseUrl("http://myserver.com")
    .addConverterFactory(GsonConverterFactory.create())
    build();
</code>

I used <b>NO multidex </b>. Any suggestion?

**Comment by at-longcb** [comment] 2016-03-16 07:36
Ya, Exactly multiDexEnabled true is the problem here. Instead of remove it, you can add make your application extends android.support.multidex.MultiDexApplication, dependence is 
dependencies {
  compile 'com.android.support:multidex:1.0.0'
}
So, To me, This is how I solve problem :)

**Comment by VishalJogiya** [comment] 2017-05-08 07:51
**at-longcb commented on 16 Mar 2016**

This one didn't work for me im still facing the same issue.
I tried removing " **multiDexEnabled true"** ,
tried adding  **compile 'com.android.support:multidex:1.0.0'**

**# But Finally I fixed this issue by extending my base Application class** 
by **_public class MyApplication extends MultiDexApplication { ... }_**
[](https://developer.android.com/studio/build/multidex.html)
