### ISSUE TITLE
Query annotation does not process curly braces correctly

### ISSUE THREAD

**Issue by alexbat98** [square/retrofit#1379] opened 2015-12-13 11:35 UTC
I'm trying to fetch data with Parse API. It uses curly braces ( `{` and `}` ) everywhere. And I'm unable to run queries that contain them. My app crashes with "java.lang.IllegalStateException: not valid as a java.net.URI"

Here is my code:
```
public interface NewsApi {
        @Headers({
                "X-Parse-Application-Id: " + APP_ID,
                "X-Parse-Master-Key: " + MASTER_KEY,
                "Content-Type: application/json"
        })
        @GET("/1/classes/news")
        Call<News> getNewsBySource(@Query("where") String source);
    }

    public static News getNewsBySource(String source) throws IOException {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(API_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        NewsApi newsApi = retrofit.create(NewsApi.class);

        Call<News> call = newsApi.getNewsBySource("{\"source\":"+source+"\"}");

        News news = call.execute().body();

        return news;
    }
```

Replacing braces with `%7B` and `%7D` doesn't help. Retrofit replaces my `%`-sign with `%25`.

**Comment by JakeWharton** [comment] 2015-12-14 01:34
Use OkHttp 2.6 with your Retrofit 2! Dupe of #1264.

**Closed by JakeWharton** 2015-12-14 01:34 UTC
