### ISSUE TITLE
Not call onError(Throwable e) method

### ISSUE THREAD

**Issue by xchengDroid** [square/retrofit#3113] opened 2019-06-03 10:27 UTC
`onError` method will not called
```java
  Observable<Response<ResponseBody>> o1 = retrofit.create(Api.class).get();
        Observable<Response<ResponseBody>> o2 = retrofit.create(Api.class).get();
        Observable.merge(o1, o2)
                .subscribeOn(Schedulers.io())
                .subscribe(new Observer<Response<ResponseBody>>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(Response<ResponseBody> responseBodyResponse) {
                        printThread("onNext:" + responseBodyResponse);
                        throw new IllegalArgumentException("Test onNext exception");
                    }

                    @Override
                    public void onError(Throwable e) {
                        printThread("onError:" + e);
                    }

                    @Override
                    public void onComplete() {
                        printThread("onComplete");
                    }
                });
```

**Comment by xchengDroid** [comment] 2019-06-04 03:48
and  no any crash message！

**Comment by JakeWharton** [comment] 2019-06-04 13:41
Dupe of https://github.com/ReactiveX/RxJava/issues/6494, presumably.

**Closed by JakeWharton** 2019-06-04 13:41 UTC
