### ISSUE TITLE
The thread in RxIoScheduler is always running after SocketTimeout by using Rxjava and Retrofit 

### ISSUE THREAD

**Issue by XiaoCaiZn** [square/retrofit#3170] opened 2019-07-18 03:04 UTC
The thread in RxIoScheduler is always running after SocketTimeout by using Rxjava and Retrofit 
 
this is how i uesd RxJava, and the timeout when create OkHttpClient was 10s.
    public static <T> void setSubscribe(Observable<T> observable, Observer<T> observer) {
        observable.subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(observer);
    }

this is Stacktrace, this exception was be catched in rx.Observer's onError, but The thread in RxIoScheduler is always running.

java.net.SocketTimeoutException: timeout
 	at okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException(FramedStream.java:600)
 	at okhttp3.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(FramedStream.java:608)
 	at okhttp3.internal.framed.FramedStream.getResponseHeaders(FramedStream.java:142)
 	at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
 	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
 	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
 	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
 	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
 	at okhttp3.z.a(RealCall.java:244)
	at okhttp3.z$a.proceed(RealCall.java:201)

Need help, thanks.

**Comment by JakeWharton** [comment] 2019-07-18 03:16
Dupe of https://github.com/ReactiveX/RxJava/issues/6578

**Closed by JakeWharton** 2019-07-18 03:16 UTC

**Comment by XiaoCaiZn** [comment] 2019-07-18 03:33
Sorry, I'm not sure this issue is need belong to.
