### ISSUE TITLE
OkHttpClient leak

### ISSUE THREAD

**Issue by g0ddest** [square/retrofit#1556] opened 2016-02-01 13:15 UTC
Have warning

`W/okhttp3.OkHttpClient: A connection to http://127.0.0.1/ was leaked. Did you forget to close a response body?`

I'm using 

com.squareup.retrofit2:retrofit:2.0.0-beta3
com.squareup.retrofit2:converter-gson:2.0.0-beta3
com.squareup.okhttp3:okhttp:3.0.0-RC1

**Comment by sohayb** [comment] 2016-02-01 13:58
I think this should be posted as an OkHttp issue.

**Comment by g0ddest** [comment] 2016-02-01 14:03
OkHttp have the same issue https://github.com/square/okhttp/issues/2158 and solve is in adding the body().string() method. I think that retrofit should automatically call this method.

**Comment by JakeWharton** [comment] 2016-02-01 14:41
Show your endpoint, `Retrofit` configuration, and calling code. Are you using `@Streaming`? This shouldn't happen unless you are using `@Streaming` and are not closing the response body.

> body().string() method. I think that retrofit should automatically call this method.

No, this would be horribly wasteful.

**Comment by jaydeep17** [comment] 2016-02-01 21:55
Same here, expect i'm using RxJava

`compile "com.squareup.retrofit2:adapter-rxjava:2.0.0-beta3"`

**Comment by JakeWharton** [comment] 2016-02-01 21:56
Show your endpoint, `Retrofit` configuration, and calling code.

**Comment by jaydeep17** [comment] 2016-02-01 22:04
Configuration code
```java
OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .addInterceptor(new AuthInterceptor(prefs)) // adds basic auth headers
        .build();
new Retrofit.Builder().baseUrl(ServerUrl.ROOT)
        .addConverterFactory(LoganSquareConverterFactory.create())
        .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
        .client(okHttpClient)
        .build();
```

Calling code
```java
@POST("register") Observable<RegistrationResponse> register(
        @Field("name") String name, @Field("email") String email
);
```

**Comment by JakeWharton** [comment] 2016-02-01 22:15
What is your interceptor doing?

**Comment by jaydeep17** [comment] 2016-02-01 22:28
here's the interceptor

```java
@Override public Response intercept(Chain chain) throws IOException {
    Request original = chain.request();
    String credentials = username + ":" + password;
    final String basic = "Basic " + Base64.encodeToString(credentials.getBytes(), Base64.NO_WRAP);
    Request.Builder requestBuilder = original.newBuilder()
        .header("Authorization", basic)
        .method(original.method(), original.body());

    Request request = requestBuilder.build();
    return chain.proceed(request);
  }
```

**Comment by JakeWharton** [comment] 2016-02-01 23:09
What version of LoganSquareConverter?

**Comment by jaydeep17** [comment] 2016-02-01 23:18
I checked it right now, they have released an update `v1.2.1`, 3 days back with the fix to this leak
Thanks :+1:

**Comment by JakeWharton** [comment] 2016-02-01 23:19
@g0ddest still need info from you as I said abaove

**Comment by g0ddest** [comment] 2016-02-02 06:14
Service

```java
    @GET("accounts/currents/")
    Call<CurrentAccountsList> getCurrentAccounts(@Query("cards") Boolean cards);
```

Configuration

```java
        class cookieInterceptor implements Interceptor {
            @Override
            public Response intercept(Chain chain)
                    throws IOException {
                Request request = chain.request();
                if(cookie != null)
                    request = request.newBuilder()
                            .removeHeader("Cookie")
                            .addHeader("Cookie", cookie)
                            .build();
                else
                    request = request.newBuilder().build();
                Response response = chain.proceed(request);
                return response;
            }
        }

        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        if(BuildConfig.DEBUG) interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(new cookieInterceptor())
                .addInterceptor(interceptor)
                .build();

        Retrofit restAdapter = new Retrofit.Builder()
                .baseUrl(BuildConfig.API_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build();
```

Calling

```java
        _api.getCurrentAccounts(Boolean.TRUE).clone().enqueue(new Callback<CurrentAccountsList>() {
            @Override
            public void onResponse(Response<CurrentAccountsList> response) {
                currentAccounts = response.body().getData();
                AccountAdapter adapter = new AccountAdapter(getBaseContext(), R.layout.account_item, currentAccounts);
                ListView accountsView = (ListView) findViewById(R.id.account_list);
                accountsView.setAdapter(adapter);
            }

            @Override
            public void onFailure(Throwable t) {}
        });
```

**Comment by JakeWharton** [comment] 2016-02-04 03:47
I cannot reproduce this. Are you sure this is the only OkHttp use in your app?

Full example:
```java
public final class Test {
  class CurrentAccountsList {}

  interface Api {
    @GET("accounts/currents/")
    Call<CurrentAccountsList> getCurrentAccounts(@Query("cards") Boolean cards);
  }

  public static void main(String... args) throws IOException, InterruptedException {
    MockWebServer server = new MockWebServer();
    server.start();
    server.enqueue(new MockResponse().setBody("{}"));

    final String cookie = "Hello";
    class cookieInterceptor implements Interceptor {
      @Override
      public okhttp3.Response intercept(Interceptor.Chain chain)
          throws IOException {
        Request request = chain.request();
        if(cookie != null)
          request = request.newBuilder()
              .removeHeader("Cookie")
              .addHeader("Cookie", cookie)
              .build();
        else
          request = request.newBuilder().build();
        okhttp3.Response response = chain.proceed(request);
        return response;
      }
    }

    HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
    if(true) interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
    OkHttpClient client = new OkHttpClient.Builder()
        .addInterceptor(new cookieInterceptor())
        .addInterceptor(interceptor)
        .build();

    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl(server.url("/"))
        .addConverterFactory(GsonConverterFactory.create())
        .client(client)
        .build();

    Api api = retrofit.create(Api.class);

    api.getCurrentAccounts(Boolean.TRUE).clone().enqueue(new Callback<CurrentAccountsList>() {
      @Override public void onResponse(Call<CurrentAccountsList> call,
          Response<CurrentAccountsList> response) {
        System.out.println("HEY");
      }

      @Override public void onFailure(Call<CurrentAccountsList> call, Throwable t) {
      }
    });

    Thread.sleep(5000);
    server.shutdown();
  }
}
```
Output:
```
Feb 03, 2016 10:45:08 PM okhttp3.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[62796] starting to accept connections
--> GET http://localhost:62796/accounts/currents/?cards=true HTTP/1.1
Cookie: Hello
--> END GET
Feb 03, 2016 10:45:09 PM okhttp3.mockwebserver.MockWebServer$4 processOneRequest
<-- 200 OK http://localhost:62796/accounts/currents/?cards=true (48ms)
Content-Length: 2
OkHttp-Sent-Millis: 1454557509431
OkHttp-Received-Millis: 1454557509438

{}
<-- END HTTP (2-byte body)
INFO: MockWebServer[62796] received request: GET /accounts/currents/?cards=true HTTP/1.1 and responded: HTTP/1.1 200 OK
HEY
Feb 03, 2016 10:45:14 PM okhttp3.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[62796] done accepting connections: Socket closed
```

**Closed** 2016-02-16 11:09 UTC
Labels: Needs Info

**Comment by sharyuke** [comment] 2016-05-06 04:46
@JakeWharton I got this error when my app crashed while post a request , so the response body will not close ,and the app did not exit .

**Comment by hsiunien** [comment] 2016-07-07 03:13
I have the same issue.after I send a request , 
after a while ,I can see the log "A connection to http://172.30.61.3:9001/ was leaked. Did you forget to close a response body?" ,ps,I use retrofit

**Comment by JerryLai8080** [comment] 2016-11-10 01:42
I got this same warning "A connection to ....was leaked ,did you forget to close a response body"
and i used retrofit too,,.it drives me crazy , shouldn't it invoked the "close " method automatically?

and i did something at the interceptor part , i add a cookies like this :+1: 

  ```
@Override
    public Response intercept(Chain chain) throws IOException {
        Response originalResponse = chain.proceed(chain.request());
        if (!isFirst) {
            if (!originalResponse.headers("Set-Cookie").isEmpty()) {
                ConstantPool.SESSION_HIDUI = originalResponse.header("Set-Cookie");
            }
        }
        isFirst = true;
        Request request = chain.request()
                .newBuilder()
                .removeHeader("Cookie")
                .addHeader("Cookie", ConstantPool.SESSION_HIDUI)
                .build();

        return chain.proceed(request);
    }
```
i guess if something wrong here?

**Comment by mandrachek** [comment] 2016-11-16 21:33
I've seen this pop up when manually executing calls, and I'm not using @Streaming at all. Specifically in the case where the request was not successful.  I needed to call response.errorBody().string() for the connection to get shut down.  

```
try {
   Call<List<SomeType>> call = retrofitService.getSomeTypes();
   Response<List<SomeType>> response = call.execute();

   if (response.isSuccessful()) {
      // calling response.body() closes the connection.
      List<SomeType> someTypeList = response.body();
   }
   else {
      // so does calling response.errorBody().string()
      // without this, the unsuccessful request doesn't close the errorBody.
      Timber.e(e,response.errorBody().string());
   }
}
catch (Exception e) {
   Timber.w(e,"An error occurred.");
}
```
