### ISSUE TITLE
Changelog of version 2.5.0 is misleading regarding Unit support

### ISSUE THREAD

**Issue by LouisCAD** [square/retrofit#3117] opened 2019-06-07 14:08 UTC
Quoting the changelog:
> New: Built-in support for Kotlin's Unit type. This behaves the same as Java's Void where the body content is ignored and immediately discarded.

If you try to use a suspending function returning no meaningly value (i.e. `Unit`), with a backend sending a 204 No-Content response for example, you end up with a *runtime* failure: the infamous `KotlinNullPointerException`.

To me, this is quite contradictory with changelog of version 2.5.0, and it's unclear how `Unit` is supported.

Also, [the test for Kotlin's `Unit`](https://github.com/square/retrofit/blob/74fc0ff863f771cde028e4bd36da70c568017a96/retrofit/src/test/java/retrofit2/KotlinUnitTest.java) is not actually written in Kotlin.

[The suspending functions support test](https://github.com/square/retrofit/blob/74fc0ff863f771cde028e4bd36da70c568017a96/retrofit/src/test/java/retrofit2/KotlinSuspendTest.kt) is in Kotlin, but it doesn't test no return value (`Unit`) in the service proxied by Retrofit. If it is not supported, it'd good to have it written clearly somewhere (along with new doc for Kotlin usage?), and a test that is asserting it fails with KNPE would be good. I lost hours of my time trying to understand why it doesn't pick the built-in `Unit` converter, and still don't have an answer, hours I'd have preferred to spend on something more useful. I prefer to not imagine how beginners would face this.

If support is not there yet, I can submit a doc update PR.

**Comment by JakeWharton** [comment] 2019-06-07 14:16
204 and 205 always return null and skip all converters for better or worse. Dupe of #2867.

> Also, the test for Kotlin's Unit is not actually written in Kotlin.

Retrofit doesn't care what language your service interfaces are written in since it parses the shape of Java bytecode through the Java reflection APIs.

> The suspending functions support test is in Kotlin, but it doesn't test no return value (Unit) in the service proxied by Retrofit.

There is no need to test this since converters are entirely orthogonal to adapters. The `Unit` converter will work in Kotlin the same as the `Optional` converter and every other built-in one. Testing every combination of converter and adapter would result in an exponential need.

**Closed by JakeWharton** 2019-06-07 14:16 UTC

**Comment by egor-n** [comment] 2019-06-07 14:29
For anyone looking for a sensible solution on how to keep using `Unit` with `suspend` functions and 204/205 responses:

```kotlin
@POST("...")
suspend fun someFun(): Response<Unit>
```

Just know that `body()` will return null as expected.

**Comment by LouisCAD** [comment] 2019-06-07 14:32
Please, try to understand the API from a usage standpoint.
You have `Call<Unit>` return type, working correctly with `await()` when the HTTP server replies 204 (or 205).
Then, you see retrofit now supports suspending functions natively, so you change all your retrofit methods to become suspending functions, and then, your program stops working properly.
Is that a great developer experience? You know the answer. That's why I believe it's important to put the emphasis on it.

For reference, here's what I found in the source code: https://github.com/square/retrofit/blob/74fc0ff863f771cde028e4bd36da70c568017a96/retrofit/src/main/java/retrofit2/HttpServiceMethod.java#L76

I understand this would need special support and why it currently doesn't work as I expected.

**Comment by LouisCAD** [comment] 2019-06-07 14:33
@egor-n That solution is not complete, because if the server responds an error, your function will not throw an `HttpException`, which is a different behavior.

**Comment by JakeWharton** [comment] 2019-06-07 14:36
> You have `Call<Unit>` return type, working correctly with `await()` when the HTTP server replies 204 (or 205).

This never actually worked as the body value will be `null` and not `Unit` in this case so your `await()` implementation was likely broken or leaked null into a non-null reference type.

**Comment by LouisCAD** [comment] 2019-06-07 14:47
Now I'm understanding my past experiences, where I had a custom `awaitSuccess()` extension function before built-in non 204/205 `Unit` support was integrated. When I updated, I tried and it didn't work, so I did a quick revert and forgot about it.

There may be less folks in my situation that I initially thought then.

**Comment by egor-n** [comment] 2019-06-07 14:47
> @egor-n That solution is not complete, because if the server responds an error, your function will not throw an HttpException, which is a different behavior.

@LouisCAD I see. You could create and throw it yourself, potentially:

```kotlin
val response = retrofitService.someFun()
if (!response.isSuccessful) throw HttpException(response)
```

**Comment by PaulWoitaschek** [comment] 2019-10-07 15:20
> There may be less folks in my situation that I initially thought then.

Well for my application every single `PUT` has no body so a function like this:

```kotlin
suspend fun putSomething()
```

Is the perfect operation of that call. I assume this is quite a common case.
