### ISSUE TITLE
Existing libraries using retrofit1 crash when main project uses retrofit2

### ISSUE THREAD

**Issue by julioromano** [square/retrofit#1209] opened 2015-10-19 10:01 UTC
This happened while including Twitterkit in an Android project that uses retrofit2.

These is the relative line in gradle:

    compile('com.twitter.sdk.android:twitter:1.8.0@aar') {
        transitive = true
    }

Twitterkit uses an old version of retrofit1 and therefore as soon as one initializes the Twitter() object in it the whole app will crash due to the incompatible API across the versions.

I'm not sure how to work around this, but maybe changing retrofit2's full class path (because it indeeds breaks compatibility with v1) could allow having both versions of the library working.

Of course library developers should upgrade the retrofit version in their libraries but what if they don't? And what if a library uses retrofit2 and the main projects is still using retrofit1?

Thanks,
Bye,
Marco

**Comment by artem-zinnatullin** [comment] 2015-10-19 13:47
Duplicate of #1152.

**Closed** 2015-12-05 04:20 UTC
