### ISSUE TITLE
SimpleXML converter XmlPullParserException in 2.1.0

### ISSUE THREAD

**Issue by ndorigatti** [square/retrofit#1892] opened 2016-07-01 13:48 UTC
I just updated from retrofit 2.0.2 to 2.1.0 (this was the only change) and got an exception while downloading Xml and converting using SimpleXML converter:

```
java.lang.RuntimeException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ﻿@1:2 in java.io.InputStreamReader@2ab51acf) 
                                                                            at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:44)
                                                                            at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:23)
                                                                            at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
                                                                            at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                                                                            at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ﻿@1:2 in java.io.InputStreamReader@2ab51acf) 
                                                                            at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
                                                                            at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
                                                                            at org.simpleframework.xml.stream.PullReader.read(PullReader.java:105)
                                                                            at org.simpleframework.xml.stream.PullReader.next(PullReader.java:89)
                                                                            at org.simpleframework.xml.stream.NodeReader.readElement(NodeReader.java:111)
                                                                            at org.simpleframework.xml.stream.NodeReader.readRoot(NodeReader.java:85)
                                                                            at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:84)
                                                                            at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:71)
                                                                            at org.simpleframework.xml.core.Persister.read(Persister.java:562)
                                                                            at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:36)
                                                                            at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:23) 
                                                                            at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117) 
                                                                            at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211) 
                                                                            at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106) 
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133) 
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                            at java.lang.Thread.run(Thread.java:818) 

```

I can't give the full XML data, but this should be the part interested in the "crash":

> <?xml version="1.0" encoding="utf-8"?>
> <publication>
> > 

If I open the xml (saved to a file to see it) using a text editor in the device I see some unknown chars (the usual square with question mark inside, don't know the name in english :D )
The issue comes with 2.1.0 switching back to 2.0.2 everything works.

**Comment by swankjesse** [comment] 2016-07-01 15:11
I'm guessing that unknown character is a BOM.

**Comment by JakeWharton** [comment] 2016-07-01 17:02
Yep. Dupe of #1875 which you can look at for a workaround for now.

**Closed by JakeWharton** 2016-07-01 17:02 UTC
