### ISSUE TITLE
MockRetrofit and coroutines

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [square/retrofit#3173] opened 2019-07-20 20:04 UTC
Is it possible to use a service like this:

```
internal interface GitHubApiService {

    @GET("users")
    suspend fun getUsers(): List<UserDTO>

    @GET("users/{username}")
    suspend fun getUser(@Path("username") username: String): UserDTO

}
```

I am getting the next error:

> Could not locate call adapter for class java.lang.Object.
>       Tried:
>        * retrofit2.CompletableFutureCallAdapterFactory
>        * retrofit2.DefaultCallAdapterFactory
>         at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:241)
>         at retrofit2.Retrofit.callAdapter(Retrofit.java:205)
>         at retrofit2.mock.BehaviorDelegate$1.invoke(BehaviorDelegate.java:64)
>         at java.lang.reflect.Proxy.invoke(Proxy.java:913)
>         at $Proxy1.getUser(Unknown Source)
>

**Comment by JakeWharton** [comment] 2019-07-20 20:05
Dupe of #3148. I've started working on this

**Closed by JakeWharton** 2019-07-20 20:05 UTC
