### ISSUE TITLE
Fatal Exception thrown on Scheduler.Worker thread

### ISSUE THREAD

**Issue by KingHanWen** [square/retrofit#1372] opened 2015-12-11 03:32 UTC
compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'

Under no circumstances network

```java

E/AndroidRuntime: FATAL EXCEPTION: main
                                                               java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                   at android.os.Handler.handleCallback(Handler.java:615)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201)
                                                                   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
                                                                   at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
                                                                   at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
                                                                   at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                   at android.os.Handler.handleCallback(Handler.java:615) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                   at android.os.Looper.loop(Looper.java:137) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201) 
                                                                   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111) 
                                                                   at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49) 
                                                                   at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49) 
                                                                   at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49) 
                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197) 
                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170) 
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                   at android.os.Handler.handleCallback(Handler.java:615) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                   at android.os.Looper.loop(Looper.java:137) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                   at android.util.Log.getStackTraceString(Log.java:314)
                                                                   at android.util.Slog.e(Slog.java:77)
                                                                   at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:72)
                                                                   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
                                                                   at android.os.Handler.handleCallback(Handler.java:615) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                   at android.os.Looper.loop(Looper.java:137) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: java.net.ConnectException: failed to connect to /218.80.1.27 (port 8443) after 10000ms: connect failed: ENETUNREACH (Network is unreachable)
                                                                   at libcore.io.IoBridge.connect(IoBridge.java:114)
                                                                   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
                                                                   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
                                                                   at java.net.Socket.connect(Socket.java:842)
                                                                   at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190)
                                                                   at com.squareup.okhttp.Connection.connectSocket(Connection.java:196)
                                                                   at com.squareup.okhttp.Connection.connect(Connection.java:172)
                                                                   at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                   at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                   at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
                                                                   at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
                                                                   at com.squareup.okhttp.Call.getResponse(Call.java:267)
                                                                   at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
                                                                   at com.yjysh.money.network.RestService.lambda$initService$14(RestService.java:111)
                                                                   at com.yjysh.money.network.RestService.access$lambda$0(RestService.java)
                                                                   at com.yjysh.money.network.RestService$$Lambda$1.intercept(Unknown Source)
                                                                   at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
                                                                   at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
                                                                   at com.squareup.okhttp.Call.execute(Call.java:79)
                                                                   at retrofit.OkHttpCall.execute(OkHttpCall.java:116)
                                                                   at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:111)
                                                                   at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:88)
                                                                   at rx.Observable.unsafeSubscribe(Observable.java:7710)
                                                                   at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                               	at java.util.concurrent.Executors$RunnableAdapter.call(Exe


```

**Comment by JakeWharton** [comment] 2015-12-11 03:37
This is a dupe of #1214, which you commented on, and it's a result of your `onError` code causing an exception when another exception occurs (in this case, a `ConnectException`). It's not a Retrofit problem.

It looks like the second exception, the one in `onError` and cause of this problem, was truncated from the end of the stack trace. Check your `onError` implementations for bugs or step through the code when the network is disconnected to find the problem.

**Closed by JakeWharton** 2015-12-11 03:37 UTC
