### ISSUE TITLE
Missing documentation and samples for Kotlin coroutines

### ISSUE THREAD

**Issue by bartek-wesolowski** [square/retrofit#3627] opened 2021-08-31 09:22 UTC
There is no documentation and samples showing how to use Retrofit with Kotlin coroutines. In particular, there should be information regarding:
- the dispatcher used with Retrofit calls and whether you should explicitly change it to Dispatchers.IO
- exception handling - what exceptions can be thrown and when; how to handle HTTP status codes

**Comment by JakeWharton** [comment] 2021-09-20 15:43
Dupe of #3263

**Closed by JakeWharton** 2021-09-20 15:43 UTC
