### ISSUE TITLE
NullPointerException: If retrofit log is enabled, DELETE api response callback throws NPE

### ISSUE THREAD

**Issue by manishgithub1173** [square/retrofit#1034] opened 2015-08-27 08:32 UTC
Log below:

D/uladder (30545): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
D/uladder (30545): 	at retrofit.RestAdapter.logResponseBody(RestAdapter.java:504)
D/uladder (30545): 	at retrofit.RestAdapter.access$600(RestAdapter.java:107)
D/uladder (30545): 	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:368)
D/uladder (30545): 	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
D/uladder (30545): 	at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
D/uladder (30545): 	at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
D/uladder (30545): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D/uladder (30545): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D/uladder (30545): 	at retrofit.Platform$Android$2$1.run(Platform.java:142)
D/uladder (30545): 	at java.lang.Thread.run(Thread.java:818)

**Comment by caseykulm** [comment] 2015-08-28 18:00
Dupe of #872.

**Comment by JakeWharton** [comment] 2015-08-31 04:07
Sorry, just don't use that log level for now. We've been heads-down on v2.0 stuff (which just released its first beta). Logging is currently being revamped. Follow the dupe chain for more info.

**Closed by JakeWharton** 2015-08-31 04:07 UTC
