### ISSUE TITLE
hey Okami,how config a default field param

### ISSUE THREAD

**Issue by ifinver** [square/retrofit#1682] opened 2016-03-17 05:16 UTC
how can I resole this,I want add two fields automatily when I reqeust from server every time,

`public interface SampleApi{
  @FormUrlEncoded
    @POST("account/login/getTlsSig") 
    Observable<UserSig> getUserSig(@Field("login_uid")String uid,@Field("login_token")String token);
}`
two fields the "login_uid" and "login_token" above, I want every Api interface contain them automatily,avoiding add filed value every time I use getUserSig.
How to do that?

**Comment by JakeWharton** [comment] 2016-03-17 05:20
This is not currently supported. Duplicate of #951.

**Closed by JakeWharton** 2016-03-17 05:20 UTC
