### ISSUE TITLE
Application getting crash with error Fatal Exception: java.lang.IllegalStateException Unbalanced enter/exit

### ISSUE THREAD

**Issue by sanketmthakare** [square/retrofit#3436] opened 2020-07-02 07:37 UTC
I am using  
 "com.squareup.retrofit2:retrofit:2.8.1" and  "com.squareup.okhttp3:logging-interceptor:4.3.1" to make web request in my android application. I am using android studio 3.6.1. Is there any D8 related issue or something else?  I am getting this issue on most of the Samsung phone. 

**Below are the logs for references.**

```
okio.AsyncTimeout.enter (AsyncTimeout.java:49)
okio.AsyncTimeout$source$1.read (AsyncTimeout.java:343)
okio.RealBufferedSource.read (RealBufferedSource.java:188)
okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read (Http1ExchangeCodec.java:352)
okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read (Http1ExchangeCodec.java:389)
okhttp3.internal.Util.skipAll (Util.java:336)
okhttp3.internal.Util.discard (Util.java:357)
okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.close (Http1ExchangeCodec.java:408)
okio.ForwardingSource.close (ForwardingSource.java:34)
okhttp3.internal.connection.Exchange$ResponseBodySource.close (Exchange.java:312)
okio.RealBufferedSource.close (RealBufferedSource.java:498)
okhttp3.internal.Util.closeQuietly (Util.java:462)
okhttp3.ResponseBody.close (ResponseBody.java:192) 
```

**Comment by JakeWharton** [comment] 2020-07-02 12:35
Dupe of https://github.com/square/okhttp/issues/6162

**Closed by JakeWharton** 2020-07-02 12:35 UTC
