### ISSUE TITLE
not valid as a java.net.URI

### ISSUE THREAD

**Issue by linwoain** [square/retrofit#1386] opened 2015-12-16 03:18 UTC
Hello, I use retrofit beta2 like this:
```gradle
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.squareup.retrofit:adapter-rxjava:2.0.0-beta2'
```
and I white an function,

```java
    @GET("http://www.xxx.com/app/api/json.php")
    Observable<NewsResp> getNewsResp(@Query("param") String param);
```
But when I post an json string as `param` 

  Caused by: java.lang.IllegalStateException: not valid as a java.net.URI: http://www.xxx.com/app/api/json.php?param={%22limit_a%22:0,%22limit_b%22:10,%22flag%22:1,%22m%22:101}

 how can I save it ??

**Comment by JakeWharton** [comment] 2015-12-16 03:20
Dupe of #1379. Upgrade to OkHttp 2.7 in your dependencies and this will be fixed.

**Closed by JakeWharton** 2015-12-16 03:20 UTC

**Comment by linwoain** [comment] 2015-12-16 08:05
thanks :+1:

**Comment by burhanshakir** [comment] 2017-04-30 18:06
Still having the same problem when using OkHttp 2.7
