### ISSUE TITLE
Non IOException in Interceptor crash the App

### ISSUE THREAD

**Issue by danielesegato** [square/retrofit#3505] opened 2020-12-22 17:56 UTC
So after banging my head on this for about half day I stumbled on this:
https://stackoverflow.com/a/58711127/902276

So, my first question is: since when do you decided that if an Interceptor throw an exception that isn't an IOException than it's a bug in the interceptor and it's a good idea to crash the app?

I throw very specific exceptions there, and I expect my app to intercept them.

I also use IOException for NETWORK ISSUE, and that's is automatically catched by my network layers to handle the auto-retry.

You are forcing me to wrap the exception in an IOException even if it's not, and than insert code in the calling layer to unwrap the exception again.

Is this specific to suspend function integration? (which I just used for the first time along with the dependency update)

I strongly disagree with this design decision, it gives nothing useful to the user, it takes away an useful feature.

EDIT: I see this is where you decided it https://github.com/square/okhttp/pull/5457

**Comment by swankjesse** [comment] 2020-12-22 18:13
Unfortunately there’s no nice way for us to propagate other exceptions through to suspending callers. The root cause is our `Callback` interface doesn’t have a place for arbitrary exceptions, only `IOException`.

Perhaps the right fix is to add a new API on okhttp3.Call, like `executeSuspending()` ?

**Comment by danielesegato** [comment] 2020-12-22 18:57
If I understand the issue correctly the problem is your `Callback` interface require an `IOException` on failure.

I'm not sure why you can't change that into `Throwable`, but can't you instead do the wrapping / unwrapping yourself?

even requiring the developer to wrap a specific exception would be more desiderable than forcing us to make the unwrapping.

Bugs are still crashing the app (meh) but at least I'm not forced to do the unwrapping myself.

**Comment by JakeWharton** [comment] 2020-12-22 20:50
I am closing because there's no action to take on Retrofit's side unless OkHttp changes its behavior. I'm very supportive of a change, I also do not like the current behavior, but our hands our tied at this level of abstraction.

We can continue a discussion at https://github.com/square/okhttp/issues/5151 or in a new OkHttp issue.

> I'm not sure why you can't change that into Throwable

Because that's a binary-incompatible change.

**Closed by JakeWharton** 2020-12-22 20:50 UTC
