### ISSUE TITLE
Null pointer exception when enable logs using .setLogLevel(RestAdapter.LogLevel.HEADERS_AND_ARGS)

### ISSUE THREAD

**Issue by akhgupta** [square/retrofit#872] opened 2015-05-31 12:01 UTC
my gradle dependencies are:
```
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
```
exception received is as below. This happens with responses with no content body
```
05-31 17:23:25.995  22366-22492/com.example.app D/Retrofit﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
            at retrofit.RestAdapter.logResponseBody(RestAdapter.java:504)
            at retrofit.RestAdapter.access$600(RestAdapter.java:107)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:368)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.logout(Unknown Source)
```

**Comment by JakeWharton** [comment] 2015-05-31 17:36
Dupe of #837. Just don't use this level for now. Things are changing rapidly.

**Closed by JakeWharton** 2015-05-31 17:36 UTC
