### ISSUE TITLE
[Feature request] Custom annotations / Spring Pageable support

### ISSUE THREAD

**Issue by adamdziedzic** [square/retrofit#3440] opened 2020-07-10 10:31 UTC
Hi,

we are using Retrofit for our backend, Spring-based apps. Spring has `Pageable` class, which is simply a wrapper for `size`, `page`, `sort` (and a few more) query params. Spring endpoint can accept `Pageable` object and create it automatically from http query.

However, if we want to pass this object to another service, we have to pass it manually, like:
```
@Query("size") size: Int,
@Query("page") page: Int,
...
```

So, we thought about making custom annotation, like `@Pageable` and pass whole object like
```
@Pageable pageable: Pageable
```
Which would look really silly, but it would save us a lot of copy-pasting. ;)

Is there a possibility for Retrofit to support custom annotations? I don't suppose that support for `Pageable` is in the scope of this project, but the possibility of extending it would be great! Or, maybe there is some way to work this out, that we didn't think of?

Thanks in advance for your help :)

**Comment by swankjesse** [comment] 2020-07-15 03:53
Add `@Tag` to the pageable parameter. Create an OkHttp interceptor that reads the tag from the request and uses it to transform the request by editing query headers.

https://square.github.io/retrofit/2.x/retrofit/

**Comment by JakeWharton** [comment] 2020-07-15 12:19
Beyond that, as a feature request, this is a duplicate of #626.

**Closed by JakeWharton** 2020-07-15 12:19 UTC
