### ISSUE TITLE
Retrofit default CallbackExecutor not executing on main thread on Android

### ISSUE THREAD

**Issue by rahul-a** [square/retrofit#1390] opened 2015-12-19 07:46 UTC
I was using mock retrofit to test dummy responses and I came across this issue that the default callback executor being used by retrofit wasn't executing on the main thread. Do we have to explicitly specify the callback executor in 2.0 as I never used to specify that before

**Comment by JakeWharton** [comment] 2015-12-19 19:12
Dupe of #1309. This is already fixed on `master` and will be in the next release.

**Closed by JakeWharton** 2015-12-19 19:12 UTC
