### ISSUE TITLE
RestAdapter.logAndReplaceResponse() crashes with EOFException with 0-byte response body

### ISSUE THREAD

**Issue by pjdelport** [square/retrofit#797] opened 2015-03-27 17:39 UTC
(Versions: okhttp **2.3.0** and retrofit **1.9.0** on Android)

I'm experiencing the following crash with Retrofit while handling certain responses from a REST API:

```
D/Retrofit: <--- HTTP 401 https://<...> (1782ms)
D/Retrofit: : HTTP/1.1 401 Unauthorized
D/Retrofit: Cache-Control: private, no-transform, must-revalidate
D/Retrofit: Connection: Keep-Alive
D/Retrofit: Content-Language: en-US
D/Retrofit: Content-Type: application/json
D/Retrofit: Date: Fri, 27 Mar 2015 11:38:06 GMT
D/Retrofit: Last-Modified: Fri, 27 Mar 2015 11:38:06 GMT
D/Retrofit: OkHttp-Received-Millis: 1427456278769
D/Retrofit: OkHttp-Response-Source: NETWORK 401
D/Retrofit: OkHttp-Selected-Protocol: http/1.1
D/Retrofit: OkHttp-Sent-Millis: 1427456278378
D/Retrofit: Transfer-Encoding: chunked
D/Retrofit: WWW-Authenticate:
[... Application-specific X-* headers omitted ...]
D/Retrofit: ---- ERROR https://<...>
D/Retrofit: java.io.EOFException
            at okio.RealBufferedSource.require(RealBufferedSource.java:67)
            at okio.GzipSource.consumeHeader(GzipSource.java:114)
            at okio.GzipSource.read(GzipSource.java:73)
            at okio.RealBufferedSource.read(RealBufferedSource.java:50)
            at okio.RealBufferedSource$1.read(RealBufferedSource.java:227)
            at java.io.InputStream.read(InputStream.java:162)
            at retrofit.Utils.streamToBytes(Utils.java:43)
            at retrofit.Utils.readBodyToBytesIfNecessary(Utils.java:81)
            at retrofit.RestAdapter.logAndReplaceResponse(RestAdapter.java:478)
            at retrofit.RestAdapter.access$500(RestAdapter.java:107)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:333)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:818)
D/Retrofit: ---- END ERROR
```

This API endpoint uses `Transfer-Encoding: chunked` for its responses, and the body of the above response is actually empty (0 bytes in size), because the 401 error details are described by API-specific HTTP response headers instead. I've only seen this crash with empty response bodies like this, so far.

As far as I can tell, the root of the problem is that `RestAdapter.logAndReplaceResponse()` causes `GzipSource` to try and decompress the body even though it is empty, which fails with `EOFException` because `GzipSource` tries to read a gzip header that isn't there.

However, I don't understand why `GzipSource` is being invoked in the first place: there is no `Content-Encoding: gzip` header in the response. The API responses should not be compressed, and the responses with non-empty bodies appear to work fine.

What exactly might be happening here? Why is `GzipSource` being invoked, instead of the body being read as an uncompressed chunked response?

**Comment by JakeWharton** [comment] 2015-04-20 00:35
Dupe of #804 (which is newer, but describes the problem better).

**Comment by JakeWharton** [comment] 2015-04-20 00:35
Fix is here: https://github.com/square/okio/pull/143

**Closed by JakeWharton** 2015-04-20 00:35 UTC
