### ISSUE TITLE
How to send a POST request with constant fields?Except custom field

### ISSUE THREAD

**Issue by Aeiric** [square/retrofit#1887] opened 2016-06-29 06:36 UTC
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by Aeiric** [comment] 2016-06-29 06:43
When there are some default fields in every request in a project,is there any good ideas not to declare in  every request.As it is not elegant.And i am bothered about that.

**Comment by JakeWharton** [comment] 2016-06-29 13:57
There is currently no support for this, and we don't really plan to add it at this time. Dupe of #951.

**Closed by JakeWharton** 2016-06-29 13:57 UTC
