### ISSUE TITLE
Not compatible with RxJava 1.20

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/retrofit#2024] opened 2016-09-21 06:54 UTC
Because of the removal of Completable.CompletableOnSubscribe RxJava, Retrofit immediately crashes when creating the adapter:

```
ava.lang.NoClassDefFoundError: Failed resolution of: Lrx/Completable$CompletableOnSubscribe;
                                                                       at retrofit2.adapter.rxjava.CompletableHelper.createCallAdapter(CompletableHelper.java:33)
                                                                       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory.get(RxJavaCallAdapterFactory.java:102)
                                                                       at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:217)
                                                                       at retrofit2.Retrofit.callAdapter(Retrofit.java:201)
                                                                       at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:232)
```
![bildschirmfoto vom 2016-09-21 08-52-16](https://cloud.githubusercontent.com/assets/743462/18700656/b903bbce-7fd8-11e6-983e-b54d45a894bd.png)

It would be great if you could provide a quick fix for this.

**Comment by JakeWharton** [comment] 2016-09-21 13:48
Already fixed on `master`. As both `Single` and `Completable` are not stable APIs it's perfectly reasonable that they broke and _not a bug_.

**Closed by JakeWharton** 2016-09-21 13:48 UTC
