### ISSUE TITLE
Can't upload file like form in html

### ISSUE THREAD

**Issue by jinksw** [square/retrofit#1078] opened 2015-09-11 07:23 UTC
here is a part of some code

i define this service method in service interface
```
public interface TestService {
@Multipart @POST("/file") Call<String> postFile(@Part("test_file")RequestBody file);
}
```

and in another place where I use this method,I create a RequestBody

and post it use code below
```
TestService testService = retrofit.create(TestService.class);
Call<String> uploadFile = testService.postFile(requestBody);
Response<String> response = uploadFile.execute();
```

I have try two method

either
```
RequestBody requestBody = RequestBody.create(MediaType.parse("application/octet-stream"), new File("/sdcard/1.png"));
```
or
```
RequestBody requestBody = new MultipartBuilder().type(MultipartBuilder.FORM)
            .addPart(Headers.of("content-Disposition", "form-data; name=\"test_file\""),
                RequestBody.create(MediaType.parse("image/png"), file))
            .build();
```
or even this, this works on okhttp.but dose not works here too.
```
RequestBody requestBody = new MultipartBuilder().type(MultipartBuilder.FORM)
            .addFormDataPart("test_file", "1.png",
                RequestBody.create(MediaType.parse("image/png"), new File("/sdcard/1.png")))
            .build();
```
can't post my file to my server.

I try to use html to post file,it works.

then I get the request header and request body from my server,I think it maybe help to find the problem.

```
D/retrofit(19811): Content-Length:105179
D/retrofit(19811): Host:192.168.1.62:1024
D/retrofit(19811): Connection:Keep-Alive
D/retrofit(19811): Content-Type:multipart/mixed; boundary=0b24a252-7f9f-40d1-94c0-04121c739b7d
D/retrofit(19811): User-Agent:okhttp/2.5.0
D/retrofit(19811): Accept-Encoding:gzip
D/retrofit(19811):
D/retrofit(19811): b'--0b24a252-7f9f-40d1-94c0-04121c739b7d\r\nContent-Disposition: name="test_file"\r\nContent-Transfer-Encoding: binary\r\nContent-Type: application/octet-stream\r\nContent-Length: 104955\r\n\r\n\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x02\x00\x00\x00\x02\x00\x08\x03\x00\x00\x00\xc3\xa6$\xc8\x00\x00\x03\x00PLTE\x00\x00\x00\xff\x00\x00\x14\x0e\x07\x1e\x12\x02\x1e\x19\r\x1d\x1a\x12#\x1b\x14)\x1d\x18# \x1c-"\x1b3%\x1d+*$\x00+\x804+",,+<,$@/(30+A0\'42"433=3)E4+B61I6-J70E9+L9.M;1;<;D<2M>9Q>3Q>9QB/UB5EC3LC2VC8CDCGE;XE7ZF9`G:]I;KJ3UJ8KKIbK>ZLBeN@hN>iOBfP?gPBlRESSSTT;UTDoTHrUFrUJZX<vYL[[Fy[Nz\\Q]]]ca<}aTbbaecJ\x83dWeeQkkk\x8ak]klPmm^\x90nassT\x92sdtt\\uurzzz{{^\x95{h\x80\x80\xff\x9a\x80l\xff\x80\x80\xff\x80\xff\x84\x81\\\x84\x84\x85\x85\x84e\x9c\x84q\x8a\x86u\xa3\x88u\x8b\x8b\x8a\x8c\x8bg\xa5\x8b{\x96\x8cf\xa6\x8e\x82\x94\x92j\xa9\x92\x82\x93\x93\x93\x98\x93\x80\x9a\x97s\x9c\x98j\xa2\x9bp\x9d\x9c\x9b\xa1\x9c|\xa2\xa2\xa2\xa5\xa3|\xa6\xa3k\xaf\xa3\x9a\xa6\xa4t\xab\xa4\x80\xff\xaa\xaa\xab\xabs\xac\xac\xac\xae\xac\x84\xad\xae{\xb2\xae\x9c\xbd\xae\x9e\xb6\xb1r\xb2\xb2\xb1\xb4\xb2|\xb2\xb4\x84\xb4\xb5\x8a\xba\xb5\x84\xbc\xb5\xaf\xc6\xb5r\xc7\xb6~\xb5\xb9\x84\xb5\xba\x8b\xb6\xbb\x92\xbb\xbb|\xcb\xbb|\xbb\xbc\x84\xbb\xbc\x8c\xbd\xbc\xbb\xce\xbc\x83\xbb\xbd\x93\xbb\xbe\x9b\xc1\xbe\x9b\xff\xbf\xbf\xbd\xc0\xa2\xc3\xc0\x82\xc7\xc0\xb7\xbd\xc1\x8d\xbd\xc1\x94\xbe\xc1\x9c\xc4\xc1\xab\xc3\xc2\x8c\xc2\xc3\x94\xd3\xc3\x85\xc2\xc4\x9c\xc3\xc4\xa2\xc5\xc4\xc4\xcb\xc4\x89\xc9\xc5\x9c\xcb\xc5\x93\xc6\xc9\x9c\xc6\xc9\xa2\xca\xcb\x94\xcb\xcb\x8c\xcf\xcb\xbd\xca\xcc\xa3\xcb\xcc\x9c\xcc\xcc\xcb\xdc\xcc\x8b\xd3\xce\x8a\xff\xcf\xdf\xd3\xd1\x94\xd1\xd3\xa5\xd3\xd3\x9b\xe0\xd3\x90\xd4\xd4\xd1\xd6\xd5\xba\xd7\xd5\xc4\xd9\xd6\x9c\xe0\xd6\xcc\xdc\xda\x93\xdb\xdb\x9c\xdb\xdb\xb6\xdf\xdb\xc8\xdc\xdc\xa4\xe1\xdc\xd4\xe5\xdc\x94\xdc\xdd\xac\xde\xdd\xdd\xe3\xe0\x9c\xe3\xe1\xa4\xeb\xe1\x93\xe3\xe2\xab\xe2\xe3\xb3\xe5\xe3\xdd\xee\xe3\x9b\xe6\xe4\xe4\xe5\xe5\xb9\xef\xe5\xa3\xe9\xe6\xab\xe6\xe9\xb4\xec\xeb\xac\xed\xeb\xc7\xec\xec\xb3\xed\xec\xa4\xed\xec\xec\xee\xec\x9b\xf2\xec\xe2\xee\xed\x94\xf1\xed\x8e\xed\xee\xbb\xf1\xee\xb3\xf2\xee\x94\xf2\xee\x9c\xf3\xee\xaa\xf4\xee\xa4\xf8\xee\xa9\xf0\xef\xbb\xf8\xef\x9d\xf8\xef\xa4\xee\xf0\x96\xee\xf1\x9a\xee\xf1\xa4\xee\xf1\xaa\xef\xf1\xb5\xf4\xf1\x8e\xf4\xf1\x95\xf5\xf2\x9c\xf5\xf2\xa4\xf4\xf3\xee\xf6\xf3\xab\xf3\xf4\xc2\xf6\xf4\xb4\xf9\xf4\x95\xf9\xf4\x9c\xf9\xf4\xa4\xf5\xf5\xba\xf9\xf5\xac\xf9\xf6\xb4\xf9\xf6\xb9\xf6\xf8\xa6\xf6\xf8\xab\xf6\xf8\xbb\xf7\xf8\xb5\xfa\xf8\x9d\xfa\xf8\xad\xfa\xf8\xb4\xf8\xf9\xc2\xfa\xf9\xa4\xfa\xf9\xb9\x00\xff\x00\x80\xff\x80\xff\xff\x00\xff\xff\xff\x00\x00\x00\xe2\xd5[\xcc\x00\x00\x01\x00tRNS\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00S\xf7\x07%\x00\x01\x00\x00IDATx\x9c\xec\xfd{tUU\x9a/\x0c\xf78\xe5\rkX9RE*\xb0wqB\xa7\x92&\xfbD:\x84\x14\xf9\xca$Fr\x8a\x06\x07\x94@\x0f\x1c\x8e\xe1\x00\xfd\x00\xf5\x08\x1c\n\x85\xe1\x0
```

I think the **multipart/mixed** in the content type is a key to find out the problem.
but I can't find out what wrong with my code .so I think it maybe,just maybe is retrofit problem?
can u help me?

**Comment by JeremiahStephenson** [comment] 2015-09-11 22:54
I'm experiencing this as well. Any workarounds?

**Comment by hansenji** [comment] 2015-09-12 00:10
This is causing a problem when trying to upgrade to 2.0

**Comment by ayon115** [comment] 2015-09-14 17:03
I have the same problem. Any workarounds ?

**Comment by JakeWharton** [comment] 2015-09-23 04:36
Dupe of #1092 which was just fixed.

**Closed by JakeWharton** 2015-09-23 04:36 UTC
