### ISSUE TITLE
"RxJava2 Adapter" jar not found

### ISSUE THREAD

**Issue by kkunsue** [square/retrofit#2209] opened 2017-02-21 10:17 UTC
- download link is broken
- can't find it in maven

**Comment by Gaket** [comment] 2017-02-21 10:21
Hi! Maybe you have similar issue I had:
http://stackoverflow.com/questions/41140203/using-rxjava-2-and-retrofit-2-adapter-version-issue/41140375

P.s. I would be glad if it helps and you add you upvote my answer)

**Comment by koala99** [comment] 2017-02-21 11:11
you should use this one:    compile 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'

**Comment by JakeWharton** [comment] 2017-02-21 15:10
Dupe of #2151.

**Closed by JakeWharton** 2017-02-21 15:10 UTC
