### ISSUE TITLE
Add support for modifying body of a POST request

### ISSUE THREAD

**Issue by pmellaaho** [square/retrofit#1182] opened 2015-10-08 09:47 UTC
So far I have been using OkHttp for my network requests but now I would like to take Retrofit (v2) into use. The server that I'm communicating with requires authToken inside a body. I also need to separate requests creation from execution which is already nicely supported as I can pass create Call<T> object and pass it forward to my requestManager (takes care of request prioritizing/queuing).

The hard part is that the authToken might not be available when a request is created and I would like to add a dummy authToken at creation time and replace it just before request is being sent. I suppose this could be done by utilizing OkHttp Interceptor but that doesn't seem like a nice solution. 

The ideal solution would be such that if I have an API like this:
Call<User> createUser(@Body User user);

It would be possible to access the body through the User API before (or even after) the execute/enqueue has been called on Call object.

**Comment by JakeWharton** [comment] 2015-10-08 15:15
This is a dupe of #816. Please add any relevant information to that issue so we can keep discussion in one place.

**Closed by JakeWharton** 2015-10-08 15:15 UTC
