### ISSUE TITLE
Character [ is not encoded in URL when using Retrofit and Gson

### ISSUE THREAD

**Issue by mink-lparrouy** [square/retrofit#3082] opened 2019-04-18 16:10 UTC
Hi there,

I'm using Retrofit to reach API endpoints. I need to use a Path parameter to execute a request, this parameter needs to be a JSON representation of an object so I decided to use Gson.

This is my JSON string : 
`"widgets":[{"label":"X "}, {"label":"Y "}]`

This is the request with the json string in the url :
 `https://xyz.com/call/%7B%22widgets%22:[%7B%22label%22`

But the part with :[ is not encoded so I get a 400.

Do you have any idea of why ? Maybe it's a OkHttp issue ?

Thank you

**Comment by JakeWharton** [comment] 2019-04-23 03:46
Dupe of #2940. I'll look into this shortly. Going to comment on that issue too.

**Closed by JakeWharton** 2019-04-23 03:46 UTC
