### ISSUE TITLE
android.os.NetworkOnMainThreadException thrown for Call.cancel()

### ISSUE THREAD

**Issue by lawloretienne** [square/retrofit#1085] opened 2015-09-15 20:18 UTC
I tried to call the method `cancel()` on a `Call` object but it throws a `android.os.NetworkOnMainThreadException`.  I thought this could be called on the main thread?

**Comment by JakeWharton** [comment] 2015-09-15 20:19
Probably a dupe of https://github.com/square/retrofit/issues/1069, and technically not Retrofit's problem. That's just the tracking issue. The problem is in OkHttp and there's an issue tracking it there as well.

**Closed by JakeWharton** 2015-09-15 20:19 UTC

**Comment by lawloretienne** [comment] 2015-09-15 20:21
Where is the OkHttp issue, so that I can follow it?  Do you have a link?

**Comment by JakeWharton** [comment] 2015-09-15 20:22
https://github.com/square/okhttp/issues/1592

**Comment by lawloretienne** [comment] 2015-09-16 02:48
Thanks.
