### ISSUE TITLE
Failed to resolve: com.squareup.retrofit2:adapter-rxjava2:2.1.0

### ISSUE THREAD

**Issue by janbolat** [square/retrofit#2153] opened 2017-01-14 15:09 UTC
Hello,
I couldn't include adapter-rxjava2 in Android Studio:
`Failed to resolve: com.squareup.retrofit2:adapter-rxjava2:2.1.0`
Also couldn't find it on [search.maven.org](https://search.maven.org/#search%7Cga%7C1%7Cadapter-rxjava2) 

UPD.
But was able to find at [oss.sonatype.org](https://oss.sonatype.org/content/repositories/snapshots/com/squareup/retrofit2/adapter-rxjava2/2.2.0-SNAPSHOT/)

**Comment by JakeWharton** [comment] 2017-01-14 21:54
Dupe of #2151.

**Closed by JakeWharton** 2017-01-14 21:54 UTC
