### ISSUE TITLE
Error: Program type already present: retrofit2.-KotlinExtensions

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail** [square/retrofit#3155] opened 2019-07-10 00:05 UTC
after android studio version 3.4.2 update, my Java project did not want to compile (even as a debug build) with retrofit version 2.5, I had to revert back to 2.4 to be able to compile the project

please note that the project is 100% java, and I did not obfuscate it ... I was running a debug build on my development device

**Comment by 09029516849** [comment] 2019-07-10 12:26
۱۳۹۸-۰۴-۱۹ ۴:۳۶ ‎+۰۴:۳۰ گرینویچ, Ahmed Adel Ismail <notifications@github.com>:

**Comment by JakeWharton** [comment] 2019-07-11 02:12
Have you done a clean build? How can I reproduce this failure? We only package a single class in the jar so the only way this could happen is some kind of misconfiguration in your build causing two versions to be packaged.

**Comment by AllanHasegawa** [comment] 2019-07-11 10:19
Had this same error message yesterday (10/July). My issue was caused by the Fabric Gradle Plugin. Their docs recommend using the version `1.+`, which is obviously a bad idea. Yesterday they launched the version "1.30.0" of the plug-in and that version broke my builds with the error above. Reverting to version "1.29.0" worked as usual.

See: https://docs.fabric.io/android/changelog.html#fabric-gradle-plugin

**Comment by slobglob** [comment] 2019-07-11 14:34
Had the same thing yesterday, tried to lower the version v1.29.0, v1.28.0 and no go

**Comment by slobglob** [comment] 2019-07-11 14:56
Hey, @AllanHasegawa tried you fix and it didn't work.
Any other solutions?

**Comment by snkashis** [comment] 2019-07-11 16:47
Same thing happened to me this morning, although I was already on fabric v1.29.0.  Tried moving to v1.30.0 and still cannot produce release APK.

**Comment by Ahmed-Adel-Ismail** [comment] 2019-07-21 11:30
Yes I did clean and invalidate cache also, but it keeps happening, once I revert back to 2.4, every thing is fine

This happened directly after updating android studio, and as I mentioned the project is pure Java

I did nothing but updating the IDE

**Comment by JakeWharton** [comment] 2019-07-22 20:04
This type isn't present in the 2.6.0 release of Retrofit so I'm going to close. No one provided a reproducer anyway.

**Closed by JakeWharton** 2019-07-22 20:04 UTC
Labels: Needs Info
