### ISSUE TITLE
Static @FormUrlEncoded @Field

### ISSUE THREAD

**Issue by osemen-remit** [square/retrofit#1495] opened 2016-01-19 14:28 UTC
Hi,
Is it possible to specify static `@FormUrlEncoded` `@Field` like it is done with headers.
For instance I have method that have some `@FormUrlEncoded` fields. And some of them are never changed or there are only few possible values and I would like to make different calls for them. Something like this:

```Java
@FormUrlEncoded
@Field("grant_type=password")
@POST("/api/login")
Call<User> login(
  @Field("username") @NonNull String username,
  @Field("password") @NonNull String password
);
```
or
```Java
@FormUrlEncoded("grant_type=password")
@POST("/api/login")
Call<User> login(
  @Field("username") @NonNull String username,
  @Field("password") @NonNull String password
);
```
Thanks.

**Comment by JakeWharton** [comment] 2016-01-19 16:41
Dupe of #951.

Very nice suggestions, though! Will use these when thinking about this feature.

**Closed by JakeWharton** 2016-01-19 16:41 UTC
