### ISSUE TITLE
Support Clean Architecture (allow API interfaces to extend other interfaces)

### ISSUE THREAD

**Issue by Raylyan** [square/retrofit#2572] opened 2017-11-25 20:28 UTC
- [ ]  Feature Request
Please allow API interfaces to extend other interfaces 

I Want to separate domain logic and retrofit platform realization on my android app in different modules. I want to do something like this

- domain module
```
interface OrderService {

    /**
     * Create new order
     *
     * @param   createOrderRequest order data
     * @return  
     */
    fun create(createOrderRequest: CreateOrderRequest): Completable

    /**
     * View order data
     *
     * @param   orderId order id
     * @return  order data
     */
    fun get(orderId: Long): Single<Order>

}
```
- retrofit platform module 
```
interface RetrofitOrderService : OrderService {

    @POST("/order/create")
    override fun create(
            @Body createOrderRequest: CreateOrderRequest
    ): Completable

    @GET("/order/get")
    override fun get(
            @Query("id") orderId: Long
    ): Single<Order>

}
```
And then use **RetrofitOrderService** injected by Dependency Injection as  **OrderService** interface
```
val orderService = retrofit.create(RetrofitOrderService::class.java) as OrderService
```
But now I catch _java.lang.IllegalArgumentException: API interfaces must not extend other interfaces_ Can you make it Optional? some thing like this:
```
 val retrofit: Retrofit = Retrofit.Builder()
            .baseUrl(BASE_URL)
            .allowApiInterfacesExtendOtherInterfaces(true)
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .addConverterFactory(ConverterFactory.create(GSON))
            .build()
```

**Comment by NightlyNexus** [comment] 2017-11-25 22:13
Duplicate of #504 ?
Perhaps consider composition and delegation over inheritance.

**Comment by JakeWharton** [comment] 2017-11-26 00:08
And specifically, this doesn't work on Android because of a Proxy bug.

**Closed by JakeWharton** 2017-11-26 00:08 UTC

**Comment by HKhademian** [comment] 2018-07-12 20:42
also by this way we can create mock services like:

```
class ProductMockService : ProductRepo {
    fun list() : Observable<Product> {
        .... fake dalays, errors, results
    }
}
```
