### ISSUE TITLE
The problem of coexistence of Gson and Simple XML

### ISSUE THREAD

**Issue by yds17322** [square/retrofit#2055] opened 2016-10-20 04:19 UTC
Because of the project requirements, there is a part of the interface is to use the XML format, there is a part of the gson format, so:

    `compile` 'com.squareup.retrofit2:converter-gson:2.1.0'
    `compile` 'com.squareup.retrofit2:converter-simplexml:2.1.0'

Two converter were introduced.
But, at the time of run, the newspaper was wrong.

`Error:Execution` failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/alto/Java/jdk1.7.0_79/bin/java'' finished with non-zero exit value 1

How to solve this problem? Thank you

**Comment by writeincodes** [comment] 2016-10-20 18:04
is there any fix? 

> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bea.xml.stream.util.CircularQueue$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:trouble processing "javax/xml/XMLConstants.class":
Error:Ill-advised or mistaken usage of a core class (java.* or javax.*)
Error:when not building a core library.
Error:This is often due to inadvertently including a core library file
Error:in your application's project, when using an IDE (such as
Error:Eclipse). If you are sure you're not intentionally defining a
Error:core class, then this is the most likely explanation of what's
Error:going on.
Error:However, you might actually be trying to define a class in a core
Error:namespace, the source of which you may have taken, for example,
Error:from a non-Android virtual machine project. This will most
Error:assuredly not work. At a minimum, it jeopardizes the
Error:compatibility of your app with future versions of the platform.
Error:It is also often of questionable legality.
Error:If you really intend to build a core library -- which is only
Error:appropriate as part of creating a full virtual machine
Error:distribution, as opposed to compiling an application -- then use
Error:the "--core-library" option to suppress this error message.
Error:If you go ahead and use "--core-library" but are in fact
Error:building an application, then be forewarned that your application
Error:will still fail to build or run, at some point. Please be
Error:prepared for angry customers who find, for example, that your
Error:application ceases to function once they upgrade their operating
Error:system. You will be to blame for this problem.
Error:If you are legitimately using some code that happens to be in a
Error:core package, then the easiest safe alternative you have is to
Error:repackage that code. That is, move the classes in question into
Error:your own package namespace. This means that they will never be in
Error:conflict with core system classes. JarJar is a tool that may help
Error:you in this endeavor. If you find that you cannot do this, then
Error:that is an indication that the path you are on will ultimately
Error:lead to pain, suffering, grief, and lamentation.

>

**Comment by JakeWharton** [comment] 2016-10-20 18:13
Dupe of #1796. This isn't a library problem but an Android build tooling problem. You can see details about working around it here: http://stackoverflow.com/a/35914651/132047

**Closed by JakeWharton** 2016-10-20 18:13 UTC
