### ISSUE TITLE
extending interfaces feature request

### ISSUE THREAD

**Issue by gavinromberger** [square/retrofit#2681] opened 2018-02-28 21:49 UTC
Feature Request

I would like to create a base api service which can be implemented in terms of generics. http://b.android.com/58753 has been resolved and while I understand that composition is the preferred pattern, inheritance can be a very powerful one. Inheritance can help with utilizing large scale consistent apis.  I have a rest api with about a hundred endpoints that all expose POST, PATCH, GET and DELETE. As it stands I have two options. 1 - create one massive service api and copy the same blocks of annotated code hundreds of times. 2 - create about a hundred service apis and still copy the same blocks of annotated code hundreds of times. This begs for inheritance. The following code is an example of the inheritance pattern I and others from what I can tell would love to see. This has been an ongoing feature request pattern for about 4 years now.

```
interface BaseService<Response, PostBody> {
    @POST("end-point")
    fun post(
        @Body body : PostBody
    ) : Call<Response>
}

interface SubService : BaseService<SubResponse, SubPostBody> {
    companion object {
        fun create(): SubService {
             val retrofit: Retrofit =  Retrofit.Builder()
                .addConverterFactory(MoshiConverterFactory.create())
                .baseUrl(SOME_URL)
                .build()
            return retrofit.create(SubService::class.java)
        }
    }
}
```

**Comment by JakeWharton** [comment] 2018-02-28 22:13
Dupe of #504. You can add your use case there. I would recommend not using Retrofit and just backing your interface with OkHttp and a serialization library directly. With dynamic request and response types, no customization of path, query, or headers, and no call adapters, Retrofit isn't providing you any value.

**Closed by JakeWharton** 2018-02-28 22:13 UTC

**Comment by gavinromberger** [comment] 2018-03-01 18:15
My actual needs include everything that you stated. Customization of path, query, headers and call adapters. I stated those needs in the feature request block. I simplified my example in an attempt to make it concise.

**Comment by gavinromberger** [comment] 2018-03-01 18:16
Ill go add my example to #504. I still hope sometime in the future you will reconsider this. Your product is awesome. This would make it that much better.
