### ISSUE TITLE
retrofit.RetrofitError: Unexpected status line: ""HTTP/1.1 204 No Content

### ISSUE THREAD

**Issue by huangcd** [square/retrofit#742] opened 2015-02-09 13:39 UTC
For the same request http://foo.com, sometimes it's OK, but sometimes it throws the following exception. When using Volley or other network debug tools, it's totally OK.
The server side is build on ASP.NET Web API

    02-09 21:31:06.524  24561-27120/com.jakata.baca D/Retrofit﹕ ---> HTTP GET http://foo.com
    02-09 21:31:06.724  24561-27120/com.jakata.baca D/Retrofit﹕ ---- ERROR http://foo.com
    02-09 21:31:06.725  24561-27120/com.jakata.baca D/Retrofit﹕ java.net.ProtocolException: Unexpected status line: ""HTTP/1.1 204 No Content
                at com.squareup.okhttp.internal.http.StatusLine.parse(StatusLine.java:53)
                at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:189)
                at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
                at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:676)
                at com.squareup.okhttp.Call.getResponse(Call.java:205)
                at com.squareup.okhttp.Call.execute(Call.java:80)
                at retrofit.client.OkClient.execute(OkClient.java:53)
                at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at retrofit.Platform$Android$2$1.run(Platform.java:142)
                at java.lang.Thread.run(Thread.java:818)
    02-09 21:31:06.725  24561-27120/com.jakata.baca D/Retrofit﹕ ---- END ERROR

**Comment by casidiablo** [comment] 2015-02-09 17:32
It looks like the status line is invalid. [See](http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html).

It seems that instead of being `HTTP/1.1 204 No Content` it is `""HTTP/1.1 204 No Content`, thus the exception.

**Comment by JakeWharton** [comment] 2015-02-09 17:37
This also could be caused by #735. Either way, it's already covered by an issue or is a misbehaving server so closing this one out.

**Closed by JakeWharton** 2015-02-09 17:37 UTC

**Comment by huangcd** [comment] 2015-02-10 12:07
Just wondering if there is any chance that somehow OkHttp didn't consume the previews request, which is an empty json string '""'. 
Any example
    
    HTTP/1.1 200 OK
    XXX
    XXX

    "" (preview request following by the error request) HTTP/1.1 204 No Content

The `HTTP/1.1 204 No Content` is just an example, which could also be 200, 404, 500

**Comment by huangcd** [comment] 2015-02-10 12:09
Just wondering if there is any chance that somehow OkHttp didn't consume the previews request, which is an empty json string '""'. 
Any example
    
    HTTP/1.1 200 OK
    XXX
    XXX

    "" (preview request following by the error request) HTTP/1.1 204 No Content

The `HTTP/1.1 204 No Content` is just an example, which could also be 200, 404, 500

**Comment by huangcd** [comment] 2015-02-10 12:52
Hi @JakeWharton , as I said before, the server was built on top of ASP.NET Web API, and behaviour correct when I'm using other network tools such as Volley, and directly visit through browser. So I think the problem is either I use OkHttp in a wrong way or there's protentially a bug.

**Comment by JakeWharton** [comment] 2015-02-10 16:38
File an issue on OkHttp.

**Comment by savepopulation** [comment] 2015-10-13 18:07
i have same problem. can you help me?

**Comment by kvsreddy3** [comment] 2016-08-17 11:01
Facing same issue..when i hit url for first time i'm getting following error org.json.JSONException: End of input at character 0 of .........For the same url if i hit second time im getting "java.net.ProtocolException: Unexpected status line: "Not Verified"HTTP/1.1 204 No Content" Exception, The same thing repeating.......Can some one please help me with this....Thanks in Advance.

**Comment by swankjesse** [comment] 2016-08-17 14:21
It sounds like a misbehaving webserver!

**Comment by AnatolyRugalev** [comment] 2018-11-19 13:48
We experience this issue with this scenario:

1. 204 Response **with body**
2. Next response gets 1st response body in the beginning of headers
3. Keep-alive is enabled.

So, the solution is to fix 204 responses to make it send no body at all.

**Comment by r-aamir** [comment] 2019-01-20 12:17
I also experience this error 
`Unexpected status line: []HTTP/1.1 204 No Content`

`204 No Content` can still hold and empty JSON object or array, I use several other clients (**iOS**: Alamofire, SwiftHTTP, **Web**: jQuery Ajax) and none of these claim this error.

I believe this has to be fixed.
