### ISSUE TITLE
[Retrofit 2.0] Gson converter keeps null values

### ISSUE THREAD

**Issue by arkaros** [square/retrofit#1094] opened 2015-09-18 17:27 UTC
So i have a request that has a body.

My gson converter is initialized like this:

```java
public static final Gson GSON = new GsonBuilder()
            .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
            .excludeFieldsWithoutExposeAnnotation()
            .registerTypeAdapter(DateTime.class, new DateTimeAdapter())
            .create();
```

I then set the Gson converter to the http client like this: 

```java
client.addConverterFactory(GsonConverterFactory.create(GSON))
```

I have an object that i called user. I want to do a patch request to the API so naturally some of the objects attributes are null and i dont want to send them at app to the API.

When i run:

```json
GSON.toJson(user)
```

The object turns out as:

```json 
{
"firstname":"Some name",
"lastname":"Some name",
"personal_number":"Some number"
}
```

But when i run it in retrofit like so:

```java
api.putUser(user)
```

It sends:

```json
{
"firstname":"Some name",
"lastname":"Some name",
"personal_number":"Some number",
"email": null,
"password": null
}
```

Is this a bugg or am i just missing simething.

The api interface is defined like this:

```java
@PATCH("users/{userId}")
Call<User> patchUser(@Body User user, @Path("userId")int userId);
```

**Comment by JakeWharton** [comment] 2015-09-18 17:33
This is a dupe of https://github.com/square/retrofit/issues/1062 and has been fixed in Gson. We're just waiting on a release to update the code.

**Closed by JakeWharton** 2015-09-18 17:33 UTC

**Comment by arkaros** [comment] 2015-09-18 17:44
Thank you for the quick reply

**Comment by masterravi** [comment] 2016-10-13 08:38
Hey @JakeWharton ,
Is this issue resolved in "com.squareup.retrofit2:retrofit:2.0.2" ??

**Comment by st4ycool** [comment] 2019-04-01 16:54
I have [same ](https://stackoverflow.com/questions/55444454/i-see-string-urltoimage-in-json-answer-but-my-gsonfactory-not-parsing-it-why) issue with `implementation 'com.squareup.retrofit2:converter-gson:2.5.0'`

**Comment by NaturalizerINA** [comment] 2020-02-25 16:17
Change your factory with this

addConverterFactory(new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create(new GsonBuilder().serializeNulls().create())))
