### ISSUE TITLE
logResponseBody produces NullPointerException

### ISSUE THREAD

**Issue by roybrener** [square/retrofit#837] opened 2015-05-11 10:33 UTC
I'm trying to make a Sync call which returns nothing using `Retrofit` 

    @DELETE("/doSomething/{uId}")
    Void doSomething(@Path("uId") String userId);

`Http status` that is returned from the server: 204 no_content. sadly i'm getting

    D/Retrofit﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
            at retrofit.RestAdapter.logResponseBody(RestAdapter.java:504)

I'm guessing because `converter.fromBody(wrapped, type);` returns null. is there a way around it beside returning value or disable the logs?

Thanks

**Comment by JakeWharton** [comment] 2015-06-04 00:38
Dupe of #716.

**Closed by JakeWharton** 2015-06-04 00:38 UTC
